import { Observable, of } from "rxjs";

import { DATASHEETS, DataSheetUri, MasterItemDefinitions, HouseItems, CraftingRecipeData, CraftingCategoryData } from "@app/nw-data";
import { Localization } from "@app/nw-buddy";

function mergeData<T>(store: Record<string, T[]>, value: Record<string, T[]>): Record<string, T[]> {
  return { ...store, ...value };
}

const translationsEnData = {
  'item_name1': 'Item Name 1',
  'item_name2': 'Item Name 2',
  'UI_ItemTypeDescription_Resource': 'Resource',
  'UI_ItemTypeDescription_HousingItem': 'Housing Item',
  'CategoryData_Resources': 'Resources',
  'CategoryData_RawResources': 'Raw Resources',
  'CategoryData_RefinedResources': 'Refined Resources',
  'IngotT52_MasterName': 'Mythril Ingot',
  'IngotT52_Description': 'Crafting Material.',
  'OreT52_MasterName': 'Mythril Ore',
  'OreT52_Description': 'Raw Resource used in crafting. Can be refined.',
  'IngotT5_MasterName': 'Orichalcum Ingot',
  'IngotT5_Description': 'Crafting Material.',
  'OreT5_MasterName': 'Orichalcum Ore',
  'OreT5_Description': 'Raw Resource used in crafting. Can be refined.',
  'IngotT4_MasterName': 'Starmetal Ingot',
  'IngotT4_Description': 'Crafting Material.',
  'OreT4_MasterName': 'Starmetal Ore',
  'OreT4_Description': 'Raw Resource used in crafting. Can be refined.',
  'IngotT3_MasterName': 'Steel Ingot',
  'IngotT3_Description': 'Crafting Material.',
  'IngotT2_MasterName': 'Iron Ingot',
  'IngotT2_Description': 'Crafting Material.',
  'OreT1_MasterName': 'Iron Ore',
  'OreT1_Description': 'Raw Resource used in crafting. Can be refined.',
  'FluxT5_MasterName': 'Obsidian Flux',
  'FluxT5_Description': 'A flux made from obsidian sand, used for smelting.',
  'ReagentConverterT5_MasterName': 'Masterwork Material Converter',
  'ReagentConverterT5_Description': 'A masterfully made, one-time-use machine that uses alchemy to convert one item to another. The process is inherently imperfect, so some loss is expected.',
  'CharcoalT1_MasterName': 'Charcoal',
  'CharcoalT1_Description': 'Crafting Material.',
  'WoodenCoin_MasterName': 'Wooden Coin',
  'WoodenCoin_Description': 'A small wooden coin found in Elite Chests, that can be used at a stonecutting station to craft heart gem runes.',
  'BeeswaxT1_MasterName': 'Beeswax',
  'BeeswaxT1_Description': 'The result of the relentless hard work of bees.',
  'AlchemyFireT1_MasterName': 'Fire Mote',
  'AlchemyFireT1_Description': 'A faint Essence of Fire. Used in Alchemy.',
  'House_HousingItem_Lighting_CandleHolder_A_MasterName': 'Rusty Iron Candelabra',
  'House_HousingItem_Lighting_CandleHolder_A_Description': 'Three tall candles, burning bright, keeping back the endless night.',
  'RefiningReagentsT5_GroupName': 'Refining Materials Tier 5',
  'Wood_CategoryName': 'Wood'
};

export function getIconPath(id: string): string {
  return `lyshineui/images/icons/items/resource/${id.toLowerCase()}.webp`;
}

export const translationsEn = Object.keys(translationsEnData).reduce<Localization>((o, k) => {
  o[k.toLowerCase()] = translationsEnData[k as keyof typeof translationsEnData];
  return o;
}, {});

export class NwBuddyApiMock {
  readonly data = {
    [DATASHEETS.MasterItemDefinitions.MasterItemDefinitions_Common.uri]: [
      {
        "ItemID": "IngotT52",
        "Name": "@IngotT52_MasterName",
        "ItemType": "Resource",
        "ItemTypeDisplayName": "@UI_ItemTypeDescription_resource",
        "Description": "@IngotT52_Description",
        "ItemClass": [
          "Resource",
          "Ingot"
        ],
        "TradingCategory": "Resources",
        "TradingFamily": "RefinedResources",
        "TradingGroup": "Ingot",
        "BindOnPickup": 0,
        "BindOnEquip": 0,
        "GearScoreOverride": 0,
        "MinGearScore": 0,
        "MaxGearScore": 0,
        "Tier": 5,
        "ForceRarity": 0,
        "RequiredLevel": 0,
        "UseMaterialAffix": 1,
        "UiItemClass": "UI_Smelting",
        "IconPath": "lyshineui/images/icons/items/resource/ingott52.webp",
        "MaxStackSize": 10000,
        "IngredientCategories": [
          "MetalT5",
          "Metal",
          "MetalT52"
        ],
        "IngredientBonusPrimary": 0,
        "IngredientBonusSecondary": 0,
        "IngredientGearScoreBaseBonus": 10,
        "IngredientGearScoreMaxBonus": 10,
        "Weight": 3,
        "NotDroppable": false
      },
      {
        "ItemID": "OreT52",
        "Name": "@OreT52_MasterName",
        "ItemType": "Resource",
        "ItemTypeDisplayName": "@UI_ItemTypeDescription_resource",
        "Description": "@OreT52_Description",
        "ItemClass": [
          "Resource",
          "Ore"
        ],
        "TradingCategory": "Resources",
        "TradingFamily": "RawResources",
        "TradingGroup": "Ore",
        "BindOnPickup": 0,
        "NoBindOnPickupChance": 0,
        "BindOnEquip": 0,
        "GearScoreOverride": 0,
        "MinGearScore": 0,
        "MaxGearScore": 0,
        "Tier": 5,
        "ForceRarity": 0,
        "RequiredLevel": 0,
        "UseMaterialAffix": 1,
        "UiItemClass": "UI_Smelting",
        "IconPath": "lyshineui/images/icons/items/resource/oret52.webp",
        "MaxStackSize": 10000,
        "IngredientBonusPrimary": 0,
        "IngredientBonusSecondary": 0,
        "IngredientGearScoreBaseBonus": 0,
        "IngredientGearScoreMaxBonus": 0,
        "Weight": 2,
        "NotDroppable": false
      },
      {
        "ItemID": "IngotT5",
        "Name": "@IngotT5_MasterName",
        "ItemType": "Resource",
        "ItemTypeDisplayName": "@UI_ItemTypeDescription_resource",
        "Description": "@IngotT5_Description",
        "ItemClass": [
          "Resource",
          "Ingot"
        ],
        "TradingCategory": "Resources",
        "TradingFamily": "RefinedResources",
        "TradingGroup": "Ingot",
        "BindOnPickup": 0,
        "NoBindOnPickupChance": 0,
        "BindOnEquip": 0,
        "GearScoreOverride": 0,
        "MinGearScore": 0,
        "MaxGearScore": 0,
        "Tier": 5,
        "ForceRarity": 0,
        "RequiredLevel": 0,
        "UseMaterialAffix": 1,
        "UiItemClass": "UI_Smelting",
        "IconPath": "lyshineui/images/icons/items/resource/ingott5.webp",
        "MaxStackSize": 10000,
        "IngredientCategories": [
          "MetalT5",
          "Metal",
          "MetalPrecious"
        ],
        "IngredientBonusPrimary": 0,
        "IngredientBonusSecondary": 0,
        "IngredientGearScoreBaseBonus": 0,
        "IngredientGearScoreMaxBonus": 0,
        "Weight": 3,
        "NotDroppable": false
      },
      {
        "ItemID": "OreT5",
        "Name": "@OreT5_MasterName",
        "ItemType": "Resource",
        "ItemTypeDisplayName": "@UI_ItemTypeDescription_resource",
        "Description": "@OreT5_Description",
        "ItemClass": [
          "Resource",
          "Ore"
        ],
        "TradingCategory": "Resources",
        "TradingFamily": "RawResources",
        "TradingGroup": "Ore",
        "BindOnPickup": 0,
        "NoBindOnPickupChance": 0,
        "BindOnEquip": 0,
        "GearScoreOverride": 0,
        "MinGearScore": 0,
        "MaxGearScore": 0,
        "Tier": 5,
        "ForceRarity": 0,
        "RequiredLevel": 0,
        "UseMaterialAffix": 1,
        "UiItemClass": "UI_Smelting",
        "IconPath": "lyshineui/images/icons/items/resource/oret5.webp",
        "MaxStackSize": 10000,
        "IngredientCategories": [
          "Ore"
        ],
        "IngredientBonusPrimary": 0,
        "IngredientBonusSecondary": 0,
        "IngredientGearScoreBaseBonus": 0,
        "IngredientGearScoreMaxBonus": 0,
        "Weight": 2,
        "NotDroppable": false
      },
      {
        "ItemID": "IngotT4",
        "Name": "@IngotT4_MasterName",
        "ItemType": "Resource",
        "ItemTypeDisplayName": "@UI_ItemTypeDescription_resource",
        "Description": "@IngotT4_Description",
        "ItemClass": [
          "Resource",
          "Ingot"
        ],
        "TradingCategory": "Resources",
        "TradingFamily": "RefinedResources",
        "TradingGroup": "Ingot",
        "BindOnPickup": 0,
        "NoBindOnPickupChance": 0,
        "BindOnEquip": 0,
        "GearScoreOverride": 0,
        "MinGearScore": 0,
        "MaxGearScore": 0,
        "Tier": 4,
        "ForceRarity": 0,
        "RequiredLevel": 0,
        "UseMaterialAffix": 1,
        "UiItemClass": "UI_Smelting",
        "IconPath": "lyshineui/images/icons/items/resource/ingott4.webp",
        "MaxStackSize": 10000,
        "IngredientCategories": [
          "MetalT4",
          "Metal"
        ],
        "IngredientBonusPrimary": 0,
        "IngredientBonusSecondary": 0,
        "IngredientGearScoreBaseBonus": 0,
        "IngredientGearScoreMaxBonus": 0,
        "Weight": 3,
        "NotDroppable": false
      },
      {
        "ItemID": "OreT4",
        "Name": "@OreT4_MasterName",
        "ItemType": "Resource",
        "ItemTypeDisplayName": "@UI_ItemTypeDescription_resource",
        "Description": "@OreT4_Description",
        "ItemClass": [
          "Resource",
          "Ore"
        ],
        "TradingCategory": "Resources",
        "TradingFamily": "RawResources",
        "TradingGroup": "Ore",
        "BindOnPickup": 0,
        "NoBindOnPickupChance": 0,
        "BindOnEquip": 0,
        "GearScoreOverride": 0,
        "MinGearScore": 0,
        "MaxGearScore": 0,
        "Tier": 4,
        "ForceRarity": 0,
        "RequiredLevel": 0,
        "UseMaterialAffix": 1,
        "UiItemClass": "UI_Smelting",
        "IconPath": "lyshineui/images/icons/items/resource/oret4.webp",
        "MaxStackSize": 10000,
        "IngredientCategories": [
          "Ore"
        ],
        "IngredientBonusPrimary": 0,
        "IngredientBonusSecondary": 0,
        "IngredientGearScoreBaseBonus": 0,
        "IngredientGearScoreMaxBonus": 0,
        "Weight": 2,
        "NotDroppable": false
      },
      {
        "ItemID": "IngotT3",
        "Name": "@IngotT3_MasterName",
        "ItemType": "Resource",
        "ItemTypeDisplayName": "@UI_ItemTypeDescription_resource",
        "Description": "@IngotT3_Description",
        "ItemClass": [
          "Resource",
          "Ingot"
        ],
        "TradingCategory": "Resources",
        "TradingFamily": "RefinedResources",
        "TradingGroup": "Ingot",
        "BindOnPickup": 0,
        "NoBindOnPickupChance": 0,
        "BindOnEquip": 0,
        "GearScoreOverride": 0,
        "MinGearScore": 0,
        "MaxGearScore": 0,
        "Tier": 3,
        "ForceRarity": 0,
        "RequiredLevel": 0,
        "UseMaterialAffix": 1,
        "UiItemClass": "UI_Smelting",
        "IconPath": "lyshineui/images/icons/items/resource/ingott3.webp",
        "MaxStackSize": 10000,
        "IngredientCategories": [
          "MetalT3",
          "Metal"
        ],
        "IngredientBonusPrimary": 0,
        "IngredientBonusSecondary": 0,
        "IngredientGearScoreBaseBonus": 0,
        "IngredientGearScoreMaxBonus": 0,
        "Weight": 3,
        "NotDroppable": false
      },
      {
        "ItemID": "IngotT2",
        "Name": "@IngotT2_MasterName",
        "ItemType": "Resource",
        "ItemTypeDisplayName": "@UI_ItemTypeDescription_resource",
        "Description": "@IngotT2_Description",
        "ItemClass": [
          "Resource",
          "Ingot"
        ],
        "TradingCategory": "Resources",
        "TradingFamily": "RefinedResources",
        "TradingGroup": "Ingot",
        "BindOnPickup": 0,
        "NoBindOnPickupChance": 0,
        "BindOnEquip": 0,
        "GearScoreOverride": 0,
        "MinGearScore": 0,
        "MaxGearScore": 0,
        "Tier": 2,
        "ForceRarity": 0,
        "RequiredLevel": 0,
        "UseMaterialAffix": 1,
        "UiItemClass": "UI_Smelting",
        "IconPath": "lyshineui/images/icons/items/resource/ingott2.webp",
        "MaxStackSize": 10000,
        "IngredientCategories": [
          "MetalT2",
          "Metal"
        ],
        "IngredientBonusPrimary": 0,
        "IngredientBonusSecondary": 0,
        "IngredientGearScoreBaseBonus": 0,
        "IngredientGearScoreMaxBonus": 0,
        "Weight": 3,
        "NotDroppable": false
      },
      {
        "ItemID": "OreT1",
        "Name": "@OreT1_MasterName",
        "ItemType": "Resource",
        "ItemTypeDisplayName": "@UI_ItemTypeDescription_resource",
        "Description": "@OreT1_Description",
        "ItemClass": [
          "Resource",
          "Ore"
        ],
        "TradingCategory": "Resources",
        "TradingFamily": "RawResources",
        "TradingGroup": "Ore",
        "BindOnPickup": 0,
        "NoBindOnPickupChance": 0,
        "BindOnEquip": 0,
        "GearScoreOverride": 0,
        "MinGearScore": 0,
        "MaxGearScore": 0,
        "Tier": 1,
        "ForceRarity": 0,
        "RequiredLevel": 0,
        "UseMaterialAffix": 1,
        "UiItemClass": "UI_Smelting",
        "IconPath": "lyshineui/images/icons/items/resource/oret1.webp",
        "MaxStackSize": 10000,
        "IngredientCategories": [
          "Ore"
        ],
        "IngredientBonusPrimary": 0,
        "IngredientBonusSecondary": 0,
        "IngredientGearScoreBaseBonus": 0,
        "IngredientGearScoreMaxBonus": 0,
        "Weight": 2,
        "NotDroppable": false
      },
      {
        "ItemID": "FluxT5",
        "Name": "@FluxT5_MasterName",
        "ItemType": "Resource",
        "ItemTypeDisplayName": "@UI_ItemTypeDescription_resource",
        "Description": "@FluxT5_Description",
        "ItemClass": [
          "Resource"
        ],
        "TradingCategory": "Resources",
        "TradingFamily": "Components",
        "TradingGroup": "RefiningComponents",
        "BindOnPickup": 0,
        "NoBindOnPickupChance": 0,
        "BindOnEquip": 0,
        "GearScoreOverride": 0,
        "MinGearScore": 0,
        "MaxGearScore": 0,
        "Tier": 5,
        "ForceRarity": 1,
        "RequiredLevel": 0,
        "UseMaterialAffix": 1,
        "UiItemClass": "UI_Refining",
        "IconPath": "lyshineui/images/icons/items/resource/fluxt5.webp",
        "MaxStackSize": 10000,
        "IngredientCategories": [
          "Flux",
          "SandpaperReagentsT5",
          "TanninReagentsT5",
          "SolventReagentsT5",
          "ClothWeaveReagentsT5"
        ],
        "IngredientBonusPrimary": 0,
        "IngredientBonusSecondary": 0,
        "IngredientGearScoreBaseBonus": 0,
        "IngredientGearScoreMaxBonus": 0,
        "Weight": 1,
        "NotDroppable": false
      },
      {
        "ItemID": "ReagentConverterT5",
        "Name": "@ReagentConverterT5_MasterName",
        "ItemType": "Resource",
        "ItemTypeDisplayName": "@UI_ItemTypeDescription_resource",
        "Description": "@ReagentConverterT5_Description",
        "ItemClass": [
          "Resource"
        ],
        "TradingCategory": "Resources",
        "TradingFamily": "Components",
        "TradingGroup": "CraftingComponents",
        "BindOnPickup": 0,
        "NoBindOnPickupChance": 0,
        "BindOnEquip": 0,
        "GearScoreOverride": 0,
        "MinGearScore": 0,
        "MaxGearScore": 0,
        "Tier": 5,
        "ForceRarity": 2,
        "RequiredLevel": 0,
        "UseMaterialAffix": 0,
        "UiItemClass": "UI_Material",
        "IconPath": "lyshineui/images/icons/items/resource/arcanereactort5.webp",
        "MaxStackSize": 10000,
        "IngredientBonusPrimary": 0,
        "IngredientBonusSecondary": 0,
        "IngredientGearScoreBaseBonus": 0,
        "IngredientGearScoreMaxBonus": 0,
        "Weight": 1,
        "NotDroppable": false
      },
      {
        "ItemID": "CharcoalT1",
        "Name": "@CharcoalT1_MasterName",
        "ItemType": "Resource",
        "ItemTypeDisplayName": "@UI_ItemTypeDescription_resource",
        "Description": "@CharcoalT1_Description",
        "ItemClass": [
          "Resource"
        ],
        "TradingCategory": "Resources",
        "TradingFamily": "RefinedResources",
        "TradingGroup": "Charcoal",
        "BindOnPickup": 0,
        "NoBindOnPickupChance": 0,
        "BindOnEquip": 0,
        "GearScoreOverride": 0,
        "MinGearScore": 0,
        "MaxGearScore": 0,
        "Tier": 2,
        "ForceRarity": 0,
        "RequiredLevel": 0,
        "UseMaterialAffix": 0,
        "UiItemClass": "UI_Smelting",
        "IconPath": "lyshineui/images/icons/items/resource/charcoalt1.webp",
        "MaxStackSize": 10000,
        "IngredientBonusPrimary": 0,
        "IngredientBonusSecondary": 0,
        "IngredientGearScoreBaseBonus": 0,
        "IngredientGearScoreMaxBonus": 0,
        "Weight": 1,
        "NotDroppable": false
      },
      {
        "ItemID": "WoodenCoin",
        "Name": "@WoodenCoin_MasterName",
        "ItemType": "Resource",
        "ItemTypeDisplayName": "@UI_ItemTypeDescription_resource",
        "Description": "@WoodenCoin_Description",
        "ItemClass": [
          "Resource"
        ],
        "TradingCategory": "Resources",
        "TradingFamily": "Components",
        "TradingGroup": "CraftingComponents",
        "BindOnPickup": 0,
        "NoBindOnPickupChance": 0,
        "BindOnEquip": 0,
        "GearScoreOverride": 0,
        "MinGearScore": 0,
        "MaxGearScore": 0,
        "Tier": 0,
        "ForceRarity": 1,
        "RequiredLevel": 0,
        "UseMaterialAffix": 0,
        "UiItemClass": "UI_Material",
        "IconPath": "lyshineui/images/icons/items/resource/mi_largegoldcoin.webp",
        "MaxStackSize": 10000,
        "IngredientBonusPrimary": 0,
        "IngredientBonusSecondary": 0,
        "IngredientGearScoreBaseBonus": 0,
        "IngredientGearScoreMaxBonus": 0,
        "Weight": 1,
        "NotDroppable": false
      },
      {
        "ItemID": "BeeswaxT1",
        "Name": "@BeeswaxT1_MasterName",
        "ItemType": "Resource",
        "ItemTypeDisplayName": "@UI_ItemTypeDescription_resource",
        "Description": "@BeeswaxT1_Description",
        "ItemClass": [
          "Resource"
        ],
        "TradingCategory": "Resources",
        "TradingFamily": "RawResources",
        "TradingGroup": "Beeswax",
        "BindOnPickup": 0,
        "NoBindOnPickupChance": 0,
        "BindOnEquip": 0,
        "GearScoreOverride": 0,
        "MinGearScore": 0,
        "MaxGearScore": 0,
        "Tier": 0,
        "ForceRarity": 0,
        "RequiredLevel": 0,
        "UseMaterialAffix": 0,
        "UiItemClass": "UI_Material",
        "IconPath": "lyshineui/images/icons/items/resource/beeswaxt1.webp",
        "MaxStackSize": 10000,
        "IngredientBonusPrimary": 0,
        "IngredientBonusSecondary": 0,
        "IngredientGearScoreBaseBonus": 0,
        "IngredientGearScoreMaxBonus": 0,
        "Weight": 1,
        "NotDroppable": false
      },
      {
        "ItemID": "AlchemyFireT1",
        "Name": "@AlchemyFireT1_MasterName",
        "ItemType": "Resource",
        "ItemTypeDisplayName": "@UI_ItemTypeDescription_resource",
        "Description": "@AlchemyFireT1_Description",
        "ItemClass": [
          "Resource",
          "Alchemy"
        ],
        "TradingCategory": "Resources",
        "TradingFamily": "ArcanaResources",
        "TradingGroup": "ArcanaFire",
        "BindOnPickup": 0,
        "NoBindOnPickupChance": 0,
        "BindOnEquip": 0,
        "GearScoreOverride": 0,
        "MinGearScore": 0,
        "MaxGearScore": 0,
        "Tier": 2,
        "ForceRarity": 0,
        "RequiredLevel": 0,
        "UseMaterialAffix": 0,
        "UiItemClass": "UI_Alchemy",
        "IconPath": "lyshineui/images/icons/items/resource/alchemyfiret1.webp",
        "MaxStackSize": 10000,
        "IngredientCategories": [
          "AlchemyFire",
          "ArcanaFire",
          "AlchemyFireT2",
          "ArcanaFireT2",
          "AlchemyProtectiveT2"
        ],
        "IngredientBonusPrimary": 0,
        "IngredientBonusSecondary": 0,
        "IngredientGearScoreBaseBonus": 0,
        "IngredientGearScoreMaxBonus": 0,
        "Weight": 1,
        "NotDroppable": false
      }
    ] satisfies Partial<MasterItemDefinitions>[],
    [DATASHEETS.HouseItems.HouseItems.uri]: [
      {
        "HouseItemID": "House_HousingItem_Lighting_CandleHolder_A",
        "UIHousingCategory": "Lighting",
        "HousingTag1 Placed": [
          "OnFurniture"
        ],
        "HousingTag2 Points": [
          "IsLighting"
        ],
        "HousingTag3 Limiter": [
          "LimiterLighting"
        ],
        "HousingTags": [
          "OnFurniture",
          "IsLighting",
          "LimiterLighting"
        ],
        "ItemRarity": "Uncommon",
        "ForceRarity": 1,
        "StorageBonus": 0,
        "Name": "@House_HousingItem_Lighting_CandleHolder_A_MasterName",
        "Description": "@House_HousingItem_Lighting_CandleHolder_A_Description",
        "IconPath": "lyshineui/images/icons/items/housingitem/house_housingitem_lighting_candleholder_a.webp",
        "Weight": 7,
        "TradingCategory": "Furnishings",
        "TradingFamily": "HousingTrdF_Decorations",
        "TradingGroup": "HousingTrdG_Lighting",
        "ItemType": "HousingItem",
        "UiItemClass": "UI_Furniture",
        "Tier": 2,
        "BindOnPickup": false,
        "MaxStackSize": 4,
        "ItemTypeDisplayName": "@UI_ItemTypeDescription_HousingItem"
      }
    ] satisfies Partial<HouseItems>[],
    [DATASHEETS.CraftingRecipeData.CraftingRecipes.uri]: [
      {
        "RecipeID": "IngotT52",
        "CraftingCategory": "RefinedResources",
        "CraftingGroup": "Metal",
        "AdditionalFilterText": "@Metal_CategoryName",
        "CraftAll": true,
        "IsRefining": true,
        "CraftingFee": 22,
        "UseCraftingTax": 0,
        "Tradeskill": "Smelting",
        "RecipeLevel": 205,
        "StationType1": "smelting2",
        "OutputQty": 1,
        "ItemID": "IngotT52",
        "SkipGrantItems": false,
        "BaseGearScore": 0,
        "BaseTier": 5,
        "Ingredient1": "OreT52",
        "Type1": "Item",
        "Ingredient2": "IngotT5",
        "Type2": "Item",
        "Ingredient3": "FluxT5",
        "Type3": "Item",
        "Ingredient4": "CharcoalT1",
        "Type4": "Item",
        "Qty1": 12,
        "Qty2": 2,
        "Qty3": 1,
        "Qty4": 2,
        "CooldownSeconds": 0,
        "CooldownQuantity": 0,
        "BonusItemChance": -0.2,
        "BonusItemChanceIncrease": "0.25,0.5,0.75,1",
        "BonusItemChanceDecrease": "-0.05,-0.1,-0.15,-0.2,-0.25",
        "PerkCost": 0
      },
      {
        "RecipeID": "IngotT5",
        "CraftingCategory": "RefinedResources",
        "CraftingGroup": "Metal",
        "AdditionalFilterText": "@Metal_CategoryName",
        "CraftAll": true,
        "IsRefining": true,
        "CraftingFee": 13,
        "UseCraftingTax": 0,
        "Tradeskill": "Smelting",
        "RecipeLevel": 150,
        "StationType1": "smelting2",
        "OutputQty": 1,
        "ItemID": "IngotT5",
        "SkipGrantItems": false,
        "BaseTier": 0,
        "Ingredient1": "OreT5",
        "Type1": "Item",
        "Ingredient2": "IngotT4",
        "Type2": "Item",
        "Ingredient3": "FluxT5",
        "Type3": "Item",
        "Ingredient4": "CharcoalT1",
        "Type4": "Item",
        "Qty1": 8,
        "Qty2": 2,
        "Qty3": 1,
        "Qty4": 2,
        "CooldownSeconds": 0,
        "CooldownQuantity": 0,
        "BonusItemChance": -0.07,
        "BonusItemChanceIncrease": "0.25,0.5,0.75,1",
        "BonusItemChanceDecrease": "-0.05,-0.1,-0.15,-0.2,-0.25"
      },
      {
        "RecipeID": "IngotT4",
        "CraftingCategory": "RefinedResources",
        "CraftingGroup": "Metal",
        "AdditionalFilterText": "@Metal_CategoryName",
        "CraftAll": true,
        "IsRefining": true,
        "CraftingFee": 7,
        "UseCraftingTax": 0,
        "Tradeskill": "Smelting",
        "RecipeLevel": 100,
        "StationType1": "smelting2",
        "OutputQty": 1,
        "ItemID": "IngotT4",
        "SkipGrantItems": false,
        "BaseTier": 0,
        "Ingredient1": "OreT4",
        "Type1": "Item",
        "Ingredient2": "IngotT3",
        "Type2": "Item",
        "Ingredient3": "FluxT5",
        "Type3": "Item",
        "Ingredient4": "CharcoalT1",
        "Type4": "Item",
        "Qty1": 6,
        "Qty2": 2,
        "Qty3": 1,
        "Qty4": 2,
        "CooldownSeconds": 0,
        "CooldownQuantity": 0,
        "BonusItemChance": -0.05,
        "BonusItemChanceIncrease": "0.25,0.5,0.75,1",
        "BonusItemChanceDecrease": "-0.05,-0.1,-0.15,-0.2,-0.25"
      },
      {
        "RecipeID": "IngotT3",
        "CraftingCategory": "RefinedResources",
        "CraftingGroup": "Metal",
        "AdditionalFilterText": "@Metal_CategoryName",
        "CraftAll": true,
        "IsRefining": true,
        "CraftingFee": 4,
        "UseCraftingTax": 0,
        "Tradeskill": "Smelting",
        "RecipeLevel": 50,
        "StationType1": "smelting2",
        "OutputQty": 1,
        "ItemID": "IngotT3",
        "SkipGrantItems": false,
        "BaseTier": 0,
        "Ingredient1": "IngotT2",
        "Type1": "Item",
        "Ingredient2": "FluxT5",
        "Type2": "Item",
        "Ingredient3": "CharcoalT1",
        "Type3": "Item",
        "Qty1": 3,
        "Qty2": 1,
        "Qty3": 2,
        "CooldownSeconds": 0,
        "CooldownQuantity": 0,
        "BonusItemChance": -0.02,
        "BonusItemChanceIncrease": "0,0.5,0.75,1",
        "BonusItemChanceDecrease": "-0.05,-0.1,-0.15,-0.2,-0.25"
      },
      {
        "RecipeID": "IngotT2",
        "CraftingCategory": "RefinedResources",
        "CraftingGroup": "Metal",
        "AdditionalFilterText": "@Metal_CategoryName",
        "CraftAll": true,
        "IsRefining": true,
        "CraftingFee": 1,
        "UseCraftingTax": 0,
        "Tradeskill": "Smelting",
        "RecipeLevel": 0,
        "StationType1": "smelting2",
        "OutputQty": 1,
        "ItemID": "IngotT2",
        "SkipGrantItems": false,
        "BaseTier": 0,
        "Ingredient1": "OreT1",
        "Type1": "Item",
        "Qty1": 4,
        "Qty2": 1,
        "CooldownSeconds": 0,
        "CooldownQuantity": 0,
        "BonusItemChance": 0,
        "BonusItemChanceIncrease": "0.25,0.5,0.75,1",
        "BonusItemChanceDecrease": "-0.05,-0.1,-0.15,-0.2,-0.25"
      },
      {
        "RecipeID": "Smelter_FluxT5",
        "CraftingCategory": "MaterialConversion",
        "CraftingGroup": "Conversion3",
        "DisplayIngredients": "ReagentConverterT5",
        "CraftAll": true,
        "IsRefining": true,
        "CraftingFee": 100,
        "UseCraftingTax": 0,
        "Tradeskill": "Smelting",
        "RecipeLevel": 0,
        "StationType1": "smelting2",
        "OutputQty": 15,
        "ItemID": "FluxT5",
        "SkipGrantItems": false,
        "BaseTier": 0,
        "Ingredient1": "ReagentConverterT5",
        "Type1": "Item",
        "Ingredient2": "FluxReagentsT5",
        "Type2": "Category_Only",
        "Qty1": 1,
        "Qty2": 20,
        "CooldownSeconds": 0,
        "CooldownQuantity": 0,
        "BonusItemChance": -0.3,
        "BonusItemChanceIncrease": "0,0,0,0,0",
        "BonusItemChanceDecrease": "0,0,0,0,0"
      },
      {
        "RecipeID": "Stonecutter_FluxT5",
        "CraftingCategory": "MaterialConversion",
        "CraftingGroup": "Conversion3",
        "DisplayIngredients": "ReagentConverterT5",
        "CraftAll": true,
        "IsRefining": true,
        "CraftingFee": 100,
        "UseCraftingTax": 0,
        "Tradeskill": "Stonecutting",
        "RecipeLevel": 0,
        "StationType1": "masonry2",
        "OutputQty": 15,
        "ItemID": "FluxT5",
        "SkipGrantItems": false,
        "BaseTier": 0,
        "Ingredient1": "ReagentConverterT5",
        "Type1": "Item",
        "Ingredient2": "FluxReagentsT5",
        "Type2": "Category_Only",
        "Qty1": 1,
        "Qty2": 20,
        "CooldownSeconds": 0,
        "CooldownQuantity": 0,
        "BonusItemChance": -0.3,
        "BonusItemChanceIncrease": "0,0,0,0,0",
        "BonusItemChanceDecrease": "0,0,0,0,0"
      },
      {
        "RecipeID": "Loom_FluxT5",
        "CraftingCategory": "MaterialConversion",
        "CraftingGroup": "Conversion3",
        "DisplayIngredients": "ReagentConverterT5",
        "CraftAll": true,
        "IsRefining": true,
        "CraftingFee": 100,
        "UseCraftingTax": 0,
        "Tradeskill": "Weaving",
        "RecipeLevel": 0,
        "StationType1": "weaving2",
        "OutputQty": 15,
        "ItemID": "FluxT5",
        "SkipGrantItems": false,
        "BaseTier": 0,
        "Ingredient1": "ReagentConverterT5",
        "Type1": "Item",
        "Ingredient2": "FluxReagentsT5",
        "Type2": "Category_Only",
        "Qty1": 1,
        "Qty2": 20,
        "CooldownSeconds": 0,
        "CooldownQuantity": 0,
        "BonusItemChance": -0.3,
        "BonusItemChanceIncrease": "0,0,0,0,0",
        "BonusItemChanceDecrease": "0,0,0,0,0"
      },
      {
        "RecipeID": "Tannery_FluxT5",
        "CraftingCategory": "MaterialConversion",
        "CraftingGroup": "Conversion3",
        "DisplayIngredients": "ReagentConverterT5",
        "CraftAll": true,
        "IsRefining": true,
        "CraftingFee": 100,
        "UseCraftingTax": 0,
        "Tradeskill": "Leatherworking",
        "RecipeLevel": 0,
        "StationType1": "tanning2",
        "OutputQty": 15,
        "ItemID": "FluxT5",
        "SkipGrantItems": false,
        "BaseTier": 0,
        "Ingredient1": "ReagentConverterT5",
        "Type1": "Item",
        "Ingredient2": "FluxReagentsT5",
        "Type2": "Category_Only",
        "Qty1": 1,
        "Qty2": 20,
        "CooldownSeconds": 0,
        "CooldownQuantity": 0,
        "BonusItemChance": -0.3,
        "BonusItemChanceIncrease": "0,0,0,0,0",
        "BonusItemChanceDecrease": "0,0,0,0,0"
      },
      {
        "RecipeID": "Woodworker_FluxT5",
        "CraftingCategory": "MaterialConversion",
        "CraftingGroup": "Conversion3",
        "DisplayIngredients": "ReagentConverterT5",
        "CraftAll": true,
        "IsRefining": true,
        "CraftingFee": 100,
        "UseCraftingTax": 0,
        "Tradeskill": "Woodworking",
        "RecipeLevel": 0,
        "StationType1": "carpentry2",
        "OutputQty": 15,
        "ItemID": "FluxT5",
        "SkipGrantItems": false,
        "BaseTier": 0,
        "Ingredient1": "ReagentConverterT5",
        "Type1": "Item",
        "Ingredient2": "FluxReagentsT5",
        "Type2": "Category_Only",
        "Qty1": 1,
        "Qty2": 20,
        "CooldownSeconds": 0,
        "CooldownQuantity": 0,
        "BonusItemChance": -0.3,
        "BonusItemChanceIncrease": "0,0,0,0,0",
        "BonusItemChanceDecrease": "0,0,0,0,0"
      },
      {
        "RecipeID": "CharcoalT1",
        "CraftingCategory": "RefinedResources",
        "CraftingGroup": "Charcoal",
        "CraftAll": true,
        "IsRefining": true,
        "CraftingFee": 1,
        "UseCraftingTax": 0,
        "Tradeskill": "Smelting",
        "RecipeLevel": 0,
        "StationType1": "smelting2",
        "OutputQty": 1,
        "ItemID": "CharcoalT1",
        "SkipGrantItems": false,
        "BaseTier": 1,
        "Ingredient1": "Wood",
        "Type1": "Category_Only",
        "Qty1": 2,
        "CooldownSeconds": 0,
        "CooldownQuantity": 0,
        "BonusItemChance": 0,
        "BonusItemChanceIncrease": "0.5,1,1.5,2,3",
        "BonusItemChanceDecrease": "0,0,0,0,0"
      },
      {
        "RecipeID": "CharcoalT1_WoodenCoin",
        "CraftingCategory": "RefinedResources",
        "CraftingGroup": "Charcoal",
        "CraftAll": true,
        "IsRefining": true,
        "CraftingFee": 1,
        "UseCraftingTax": 0,
        "Tradeskill": "Smelting",
        "RecipeLevel": 75,
        "StationType1": "smelting2",
        "OutputQty": 10,
        "ItemID": "CharcoalT1",
        "SkipGrantItems": false,
        "BaseTier": 1,
        "Ingredient1": "WoodenCoin",
        "Type1": "Item",
        "Qty1": 1,
        "CooldownSeconds": 0,
        "CooldownQuantity": 0,
        "BonusItemChance": 0,
        "BonusItemChanceIncrease": "0.5,1,1.5,2,3",
        "BonusItemChanceDecrease": "0,0,0,0,0"
      }
    ] satisfies Partial<CraftingRecipeData>[],
    [DATASHEETS.CraftingCategoryData.CraftingCategories.uri]: [
      {
        "CategoryID": "FluxReagentsT5",
        "ImagePath": "lyshineui/images/icons/items/drawing/refiningreagents.webp",
        "DisplayText": "@RefiningReagentsT5_GroupName"
      },
      {
        "CategoryID": "Wood",
        "ImagePath": "lyshineui/images/icons/items/drawing/wood.webp",
        "DisplayText": "@Wood_CategoryName"
      }
    ] satisfies Partial<CraftingCategoryData>[]
  };

  private readonly _getDataSheet = <T>([key, value]: [string, DataSheetUri<T>]): Record<string, T[]> => {
    return { [key]: this.data[value.uri] as T[] };
  }

  getTranslations(locale: string): Observable<Localization> {
    return of(locale === 'en-us' ? translationsEn : {});
  }

  getDataSheets<T>(set: Record<string, DataSheetUri<T>>): Observable<Record<string, T[]>> {
    return of(Object.entries(set).map(this._getDataSheet).reduce(mergeData, {}));
  }
}
