import { inject } from '@angular/core';
import { firstValueFrom, from, mergeMap, Observable, of, reduce, timer } from 'rxjs';

import { DATASHEETS, DataSheetUri, MasterItemDefinitions, HouseItems, CraftingRecipeData, CraftingCategoryData, ItemType } from '@app/nw-data';
import { Localization, NwI18n } from '@app/nw-buddy';
import { AsyncManager } from './async-manager';

function mergeData<T>(store: Record<string, T[]>, value: Record<string, T[]>): Record<string, T[]> {
  return { ...store, ...value };
}

const translationsEnData = {
  'item_name1': 'Item Name 1',
  'item_name2': 'Item Name 2',
  'UI_ItemTypeDescription_Resource': 'Resource',
  'UI_ItemTypeDescription_HousingItem': 'Housing Item',
  'CategoryData_Resources': 'Resources',
  'CategoryData_RawResources': 'Raw Resources',
  'CategoryData_RefinedResources': 'Refined Resources',
  'IngotT52_MasterName': 'Mythril Ingot',
  'IngotT52_Description': 'Crafting Material.',
  'OreT52_MasterName': 'Mythril Ore',
  'OreT52_Description': 'Raw Resource used in crafting. Can be refined.',
  'IngotT5_MasterName': 'Orichalcum Ingot',
  'IngotT5_Description': 'Crafting Material.',
  'OreT5_MasterName': 'Orichalcum Ore',
  'OreT5_Description': 'Raw Resource used in crafting. Can be refined.',
  'IngotT4_MasterName': 'Starmetal Ingot',
  'IngotT4_Description': 'Crafting Material.',
  'OreT4_MasterName': 'Starmetal Ore',
  'OreT4_Description': 'Raw Resource used in crafting. Can be refined.',
  'IngotT3_MasterName': 'Steel Ingot',
  'IngotT3_Description': 'Crafting Material.',
  'IngotT2_MasterName': 'Iron Ingot',
  'IngotT2_Description': 'Crafting Material.',
  'OreT1_MasterName': 'Iron Ore',
  'OreT1_Description': 'Raw Resource used in crafting. Can be refined.',
  'FluxT5_MasterName': 'Obsidian Flux',
  'FluxT5_Description': 'A flux made from obsidian sand, used for smelting.',
  'ReagentConverterT5_MasterName': 'Masterwork Material Converter',
  'ReagentConverterT5_Description': 'A masterfully made, one-time-use machine that uses alchemy to convert one item to another. The process is inherently imperfect, so some loss is expected.',
  'CharcoalT1_MasterName': 'Charcoal',
  'CharcoalT1_Description': 'Crafting Material.',
  'WoodenCoin_MasterName': 'Wooden Coin',
  'WoodenCoin_Description': 'A small wooden coin found in Elite Chests, that can be used at a stonecutting station to craft heart gem runes.',
  'BeeswaxT1_MasterName': 'Beeswax',
  'BeeswaxT1_Description': 'The result of the relentless hard work of bees.',
  'AlchemyFireT1_MasterName': 'Fire Mote',
  'AlchemyFireT1_Description': 'A faint Essence of Fire. Used in Alchemy.',
  'House_HousingItem_Lighting_CandleHolder_A_MasterName': 'Rusty Iron Candelabra',
  'House_HousingItem_Lighting_CandleHolder_A_Description': 'Three tall candles, burning bright, keeping back the endless night.',
  'RefiningReagentsT5_GroupName': 'Refining Materials Tier 5',
  'Wood_CategoryName': 'Wood'
};

export function getIconPath(type: ItemType, id: string): string {
  return `lyshineui/images/icons/items/${type.toLowerCase()}/${id.toLowerCase()}.webp`;
}

export const translationsEn = Object.keys(translationsEnData).reduce<Localization>((o, k) => {
  o[k.toLowerCase()] = translationsEnData[k as keyof typeof translationsEnData];
  return o;
}, {});

export function getDatasheetIds<T>(set: Record<string, DataSheetUri<T>>): string[] {
  return Object.keys(set).map(key => key);
}

type MasterItemDefinitionsProps =
  | "ItemID"
  | "Name"
  | "ItemType"
  | "ItemTypeDisplayName"
  | "Description"
  | "ItemClass"
  | "TradingCategory"
  | "TradingFamily"
  | "TradingGroup"
  | "BindOnPickup"
  | "NoBindOnPickupChance"
  | "BindOnEquip"
  | "GearScoreOverride"
  | "MinGearScore"
  | "MaxGearScore"
  | "Tier"
  | "ForceRarity"
  | "RequiredLevel"
  | "UseMaterialAffix"
  | "UiItemClass"
  | "IconPath"
  | "MaxStackSize"
  | "IngredientCategories"
  | "IngredientBonusPrimary"
  | "IngredientBonusSecondary"
  | "IngredientGearScoreBaseBonus"
  | "IngredientGearScoreMaxBonus"
  | "Weight"
  | "NotDroppable";

type MasterItemDefinitionsTestData = Pick<MasterItemDefinitions, MasterItemDefinitionsProps>;

type HouseItemsProps =
  | "HouseItemID"
  | "UIHousingCategory"
  | "HousingTag1 Placed"
  | "HousingTag2 Points"
  | "HousingTag3 Limiter"
  | "HousingTags"
  | "ItemRarity"
  | "ForceRarity"
  | "StorageBonus"
  | "Name"
  | "Description"
  | "IconPath"
  | "Weight"
  | "TradingCategory"
  | "TradingFamily"
  | "TradingGroup"
  | "ItemType"
  | "UiItemClass"
  | "Tier"
  | "BindOnPickup"
  | "MaxStackSize"
  | "ItemTypeDisplayName";

type HouseItemsTestData = Pick<HouseItems, HouseItemsProps>;

type CraftingRecipeDataProps =
  | "RecipeID"
  | "CraftingCategory"
  | "CraftingGroup"
  | "DisplayIngredients"
  | "AdditionalFilterText"
  | "CraftAll"
  | "IsRefining"
  | "CraftingFee"
  | "UseCraftingTax"
  | "Tradeskill"
  | "RecipeLevel"
  | "StationType1"
  | "OutputQty"
  | "ItemID"
  | "SkipGrantItems"
  | "BaseGearScore"
  | "BaseTier"
  | "Ingredient1"
  | "Ingredient2"
  | "Ingredient3"
  | "Ingredient4"
  | "Ingredient5"
  | "Ingredient6"
  | "Ingredient7"
  | "Qty1"
  | "Qty2"
  | "Qty3"
  | "Qty4"
  | "Qty5"
  | "Qty6"
  | "Qty7"
  | "Type1"
  | "Type2"
  | "Type3"
  | "Type4"
  | "Type5"
  | "Type6"
  | "Type7"
  | "CooldownSeconds"
  | "CooldownQuantity"
  | "BonusItemChance"
  | "BonusItemChanceIncrease"
  | "BonusItemChanceDecrease"
  | "PerkCost";

type CraftingRecipeTestData = Pick<CraftingRecipeData, CraftingRecipeDataProps>;

type CraftingCategoryDataProps =
  | "CategoryID"
  | "ImagePath"
  | "DisplayText";

type CraftingCategoryTestData = Pick<CraftingCategoryData, CraftingCategoryDataProps>;

export async function initializeNwBuddy() {
  const i18n = inject(NwI18n);
  while (i18n.isLoading()) {
    await firstValueFrom(timer(100));
  }
}

export class NwBuddyApiMock {
  readonly #async = new AsyncManager();

  readonly data = {
    [DATASHEETS.MasterItemDefinitions.MasterItemDefinitions_Common.uri]: [
      {
        "ItemID": "AzureT1",
        "Name": "@AzureT1_MasterName",
        "ItemType": "Resource",
        "ItemTypeDisplayName": "@ui_itemtypedescription_resource",
        "Description": "@AzureT1_Description",
        "ItemClass": ["Resource"],
        "BindOnPickup": 0,
        "NoBindOnPickupChance": 0,
        "BindOnEquip": 0,
        "GearScoreOverride": 0,
        "MinGearScore": 0,
        "MaxGearScore": 0,
        "Tier": 0,
        "ForceRarity": 0,
        "RequiredLevel": 0,
        "UseMaterialAffix": 0,
        "UiItemClass": "UI_Material",
        "IconPath": "lyshineui/images/icons/items/resource/azuret1.webp",
        "MaxStackSize": 10000,
        "IngredientBonusPrimary": 0,
        "IngredientBonusSecondary": 0,
        "IngredientGearScoreBaseBonus": 0,
        "IngredientGearScoreMaxBonus": 0,
        "Weight": 1,
        "NotDroppable": false
      },
      {
        "ItemID": "WoodT1",
        "Name": "@WoodT1_MasterName",
        "ItemType": "Resource",
        "ItemTypeDisplayName": "@UI_ItemTypeDescription_Resource",
        "Description": "@WoodT1_Description",
        "ItemClass": [
          "Resource",
          "Wood"
        ],
        "TradingCategory": "Resources",
        "TradingFamily": "RawResources",
        "TradingGroup": "Wood",
        "BindOnPickup": 0,
        "NoBindOnPickupChance": 0,
        "BindOnEquip": 0,
        "GearScoreOverride": 0,
        "MinGearScore": 0,
        "MaxGearScore": 0,
        "Tier": 1,
        "ForceRarity": 0,
        "RequiredLevel": 0,
        "UseMaterialAffix": 1,
        "UiItemClass": "UI_Woodworking",
        "IconPath": "lyshineui/images/icons/items/resource/woodt1.webp",
        "MaxStackSize": 10000,
        "IngredientCategories": [
          "Wood"
        ],
        "IngredientBonusPrimary": 0,
        "IngredientBonusSecondary": 0,
        "IngredientGearScoreBaseBonus": 0,
        "IngredientGearScoreMaxBonus": 0,
        "Weight": 2,
        "NotDroppable": false
      },
      {
        "ItemID": "WoodT2",
        "Name": "@WoodT2_MasterName",
        "ItemType": "Resource",
        "ItemTypeDisplayName": "@UI_ItemTypeDescription_Resource",
        "Description": "@WoodT2_Description",
        "ItemClass": [
          "Resource",
          "Wood"
        ],
        "TradingCategory": "Resources",
        "TradingFamily": "RawResources",
        "TradingGroup": "Wood",
        "BindOnPickup": 0,
        "NoBindOnPickupChance": 0,
        "BindOnEquip": 0,
        "GearScoreOverride": 0,
        "MinGearScore": 0,
        "MaxGearScore": 0,
        "Tier": 2,
        "ForceRarity": 0,
        "RequiredLevel": 0,
        "UseMaterialAffix": 1,
        "UiItemClass": "UI_Woodworking",
        "IconPath": "lyshineui/images/icons/items/resource/woodt2.webp",
        "MaxStackSize": 10000,
        "IngredientCategories": [
          "Wood"
        ],
        "IngredientBonusPrimary": 0,
        "IngredientBonusSecondary": 0,
        "IngredientGearScoreBaseBonus": 0,
        "IngredientGearScoreMaxBonus": 0,
        "Weight": 2,
        "NotDroppable": false
      },
      {
        "ItemID": "WoodT4",
        "Name": "@WoodT4_MasterName",
        "ItemType": "Resource",
        "ItemTypeDisplayName": "@UI_ItemTypeDescription_Resource",
        "Description": "@WoodT4_Description",
        "ItemClass": [
          "Resource",
          "Wood"
        ],
        "TradingCategory": "Resources",
        "TradingFamily": "RawResources",
        "TradingGroup": "Wood",
        "BindOnPickup": 0,
        "NoBindOnPickupChance": 0,
        "BindOnEquip": 0,
        "GearScoreOverride": 0,
        "MinGearScore": 0,
        "MaxGearScore": 0,
        "Tier": 4,
        "ForceRarity": 0,
        "RequiredLevel": 0,
        "UseMaterialAffix": 1,
        "UiItemClass": "UI_Woodworking",
        "IconPath": "lyshineui/images/icons/items/resource/woodt4.webp",
        "MaxStackSize": 10000,
        "IngredientCategories": [
          "Wood"
        ],
        "IngredientBonusPrimary": 0,
        "IngredientBonusSecondary": 0,
        "IngredientGearScoreBaseBonus": 0,
        "IngredientGearScoreMaxBonus": 0,
        "Weight": 2,
        "NotDroppable": false
      },
      {
        "ItemID": "WoodT5",
        "Name": "@WoodT5_MasterName",
        "ItemType": "Resource",
        "ItemTypeDisplayName": "@UI_ItemTypeDescription_Resource",
        "Description": "@WoodT5_Description",
        "ItemClass": [
          "Resource",
          "Wood"
        ],
        "TradingCategory": "Resources",
        "TradingFamily": "RawResources",
        "TradingGroup": "Wood",
        "BindOnPickup": 0,
        "NoBindOnPickupChance": 0,
        "BindOnEquip": 0,
        "GearScoreOverride": 0,
        "MinGearScore": 0,
        "MaxGearScore": 0,
        "Tier": 5,
        "ForceRarity": 0,
        "RequiredLevel": 0,
        "UseMaterialAffix": 1,
        "UiItemClass": "UI_Woodworking",
        "IconPath": "lyshineui/images/icons/items/resource/woodt5.webp",
        "MaxStackSize": 10000,
        "IngredientCategories": [
          "Wood"
        ],
        "IngredientBonusPrimary": 0,
        "IngredientBonusSecondary": 0,
        "IngredientGearScoreBaseBonus": 0,
        "IngredientGearScoreMaxBonus": 0,
        "Weight": 2,
        "NotDroppable": false
      },
      {
        "ItemID": "WoodT52",
        "Name": "@WoodT52_MasterName",
        "ItemType": "Resource",
        "ItemTypeDisplayName": "@UI_ItemTypeDescription_Resource",
        "Description": "@WoodT52_Description",
        "ItemClass": [
          "Resource",
          "Wood"
        ],
        "TradingCategory": "Resources",
        "TradingFamily": "RawResources",
        "TradingGroup": "Wood",
        "BindOnPickup": 0,
        "NoBindOnPickupChance": 0,
        "BindOnEquip": 0,
        "GearScoreOverride": 0,
        "MinGearScore": 0,
        "MaxGearScore": 0,
        "Tier": 5,
        "ForceRarity": 0,
        "RequiredLevel": 0,
        "UseMaterialAffix": 1,
        "UiItemClass": "UI_Woodworking",
        "IconPath": "lyshineui/images/icons/items/resource/woodt52.webp",
        "MaxStackSize": 10000,
        "IngredientCategories": [
          "Wood"
        ],
        "IngredientBonusPrimary": 0,
        "IngredientBonusSecondary": 0,
        "IngredientGearScoreBaseBonus": 0,
        "IngredientGearScoreMaxBonus": 0,
        "Weight": 2,
        "NotDroppable": false
      },
      {
        "ItemID": "IngotT52",
        "Name": "@IngotT52_MasterName",
        "ItemType": "Resource",
        "ItemTypeDisplayName": "@UI_ItemTypeDescription_Resource",
        "Description": "@IngotT52_Description",
        "ItemClass": [
          "Resource",
          "Ingot"
        ],
        "TradingCategory": "Resources",
        "TradingFamily": "RefinedResources",
        "TradingGroup": "Ingot",
        "BindOnPickup": 0,
        "BindOnEquip": 0,
        "GearScoreOverride": 0,
        "MinGearScore": 0,
        "MaxGearScore": 0,
        "Tier": 5,
        "ForceRarity": 0,
        "RequiredLevel": 0,
        "UseMaterialAffix": 1,
        "UiItemClass": "UI_Smelting",
        "IconPath": "lyshineui/images/icons/items/resource/ingott52.webp",
        "MaxStackSize": 10000,
        "IngredientCategories": [
          "MetalT5",
          "Metal",
          "MetalT52"
        ],
        "IngredientBonusPrimary": 0,
        "IngredientBonusSecondary": 0,
        "IngredientGearScoreBaseBonus": 10,
        "IngredientGearScoreMaxBonus": 10,
        "Weight": 3,
        "NotDroppable": false
      },
      {
        "ItemID": "OreT52",
        "Name": "@OreT52_MasterName",
        "ItemType": "Resource",
        "ItemTypeDisplayName": "@UI_ItemTypeDescription_Resource",
        "Description": "@OreT52_Description",
        "ItemClass": [
          "Resource",
          "Ore"
        ],
        "TradingCategory": "Resources",
        "TradingFamily": "RawResources",
        "TradingGroup": "Ore",
        "BindOnPickup": 0,
        "NoBindOnPickupChance": 0,
        "BindOnEquip": 0,
        "GearScoreOverride": 0,
        "MinGearScore": 0,
        "MaxGearScore": 0,
        "Tier": 5,
        "ForceRarity": 0,
        "RequiredLevel": 0,
        "UseMaterialAffix": 1,
        "UiItemClass": "UI_Smelting",
        "IconPath": "lyshineui/images/icons/items/resource/oret52.webp",
        "MaxStackSize": 10000,
        "IngredientBonusPrimary": 0,
        "IngredientBonusSecondary": 0,
        "IngredientGearScoreBaseBonus": 0,
        "IngredientGearScoreMaxBonus": 0,
        "Weight": 2,
        "NotDroppable": false
      },
      {
        "ItemID": "IngotT5",
        "Name": "@IngotT5_MasterName",
        "ItemType": "Resource",
        "ItemTypeDisplayName": "@UI_ItemTypeDescription_Resource",
        "Description": "@IngotT5_Description",
        "ItemClass": [
          "Resource",
          "Ingot"
        ],
        "TradingCategory": "Resources",
        "TradingFamily": "RefinedResources",
        "TradingGroup": "Ingot",
        "BindOnPickup": 0,
        "NoBindOnPickupChance": 0,
        "BindOnEquip": 0,
        "GearScoreOverride": 0,
        "MinGearScore": 0,
        "MaxGearScore": 0,
        "Tier": 5,
        "ForceRarity": 0,
        "RequiredLevel": 0,
        "UseMaterialAffix": 1,
        "UiItemClass": "UI_Smelting",
        "IconPath": "lyshineui/images/icons/items/resource/ingott5.webp",
        "MaxStackSize": 10000,
        "IngredientCategories": [
          "MetalT5",
          "Metal",
          "MetalPrecious"
        ],
        "IngredientBonusPrimary": 0,
        "IngredientBonusSecondary": 0,
        "IngredientGearScoreBaseBonus": 0,
        "IngredientGearScoreMaxBonus": 0,
        "Weight": 3,
        "NotDroppable": false
      },
      {
        "ItemID": "OreT5",
        "Name": "@OreT5_MasterName",
        "ItemType": "Resource",
        "ItemTypeDisplayName": "@UI_ItemTypeDescription_Resource",
        "Description": "@OreT5_Description",
        "ItemClass": [
          "Resource",
          "Ore"
        ],
        "TradingCategory": "Resources",
        "TradingFamily": "RawResources",
        "TradingGroup": "Ore",
        "BindOnPickup": 0,
        "NoBindOnPickupChance": 0,
        "BindOnEquip": 0,
        "GearScoreOverride": 0,
        "MinGearScore": 0,
        "MaxGearScore": 0,
        "Tier": 5,
        "ForceRarity": 0,
        "RequiredLevel": 0,
        "UseMaterialAffix": 1,
        "UiItemClass": "UI_Smelting",
        "IconPath": "lyshineui/images/icons/items/resource/oret5.webp",
        "MaxStackSize": 10000,
        "IngredientCategories": [
          "Ore"
        ],
        "IngredientBonusPrimary": 0,
        "IngredientBonusSecondary": 0,
        "IngredientGearScoreBaseBonus": 0,
        "IngredientGearScoreMaxBonus": 0,
        "Weight": 2,
        "NotDroppable": false
      },
      {
        "ItemID": "IngotT4",
        "Name": "@IngotT4_MasterName",
        "ItemType": "Resource",
        "ItemTypeDisplayName": "@UI_ItemTypeDescription_Resource",
        "Description": "@IngotT4_Description",
        "ItemClass": [
          "Resource",
          "Ingot"
        ],
        "TradingCategory": "Resources",
        "TradingFamily": "RefinedResources",
        "TradingGroup": "Ingot",
        "BindOnPickup": 0,
        "NoBindOnPickupChance": 0,
        "BindOnEquip": 0,
        "GearScoreOverride": 0,
        "MinGearScore": 0,
        "MaxGearScore": 0,
        "Tier": 4,
        "ForceRarity": 0,
        "RequiredLevel": 0,
        "UseMaterialAffix": 1,
        "UiItemClass": "UI_Smelting",
        "IconPath": "lyshineui/images/icons/items/resource/ingott4.webp",
        "MaxStackSize": 10000,
        "IngredientCategories": [
          "MetalT4",
          "Metal"
        ],
        "IngredientBonusPrimary": 0,
        "IngredientBonusSecondary": 0,
        "IngredientGearScoreBaseBonus": 0,
        "IngredientGearScoreMaxBonus": 0,
        "Weight": 3,
        "NotDroppable": false
      },
      {
        "ItemID": "OreT4",
        "Name": "@OreT4_MasterName",
        "ItemType": "Resource",
        "ItemTypeDisplayName": "@UI_ItemTypeDescription_Resource",
        "Description": "@OreT4_Description",
        "ItemClass": [
          "Resource",
          "Ore"
        ],
        "TradingCategory": "Resources",
        "TradingFamily": "RawResources",
        "TradingGroup": "Ore",
        "BindOnPickup": 0,
        "NoBindOnPickupChance": 0,
        "BindOnEquip": 0,
        "GearScoreOverride": 0,
        "MinGearScore": 0,
        "MaxGearScore": 0,
        "Tier": 4,
        "ForceRarity": 0,
        "RequiredLevel": 0,
        "UseMaterialAffix": 1,
        "UiItemClass": "UI_Smelting",
        "IconPath": "lyshineui/images/icons/items/resource/oret4.webp",
        "MaxStackSize": 10000,
        "IngredientCategories": [
          "Ore"
        ],
        "IngredientBonusPrimary": 0,
        "IngredientBonusSecondary": 0,
        "IngredientGearScoreBaseBonus": 0,
        "IngredientGearScoreMaxBonus": 0,
        "Weight": 2,
        "NotDroppable": false
      },
      {
        "ItemID": "IngotT3",
        "Name": "@IngotT3_MasterName",
        "ItemType": "Resource",
        "ItemTypeDisplayName": "@UI_ItemTypeDescription_Resource",
        "Description": "@IngotT3_Description",
        "ItemClass": [
          "Resource",
          "Ingot"
        ],
        "TradingCategory": "Resources",
        "TradingFamily": "RefinedResources",
        "TradingGroup": "Ingot",
        "BindOnPickup": 0,
        "NoBindOnPickupChance": 0,
        "BindOnEquip": 0,
        "GearScoreOverride": 0,
        "MinGearScore": 0,
        "MaxGearScore": 0,
        "Tier": 3,
        "ForceRarity": 0,
        "RequiredLevel": 0,
        "UseMaterialAffix": 1,
        "UiItemClass": "UI_Smelting",
        "IconPath": "lyshineui/images/icons/items/resource/ingott3.webp",
        "MaxStackSize": 10000,
        "IngredientCategories": [
          "MetalT3",
          "Metal"
        ],
        "IngredientBonusPrimary": 0,
        "IngredientBonusSecondary": 0,
        "IngredientGearScoreBaseBonus": 0,
        "IngredientGearScoreMaxBonus": 0,
        "Weight": 3,
        "NotDroppable": false
      },
      {
        "ItemID": "IngotT2",
        "Name": "@IngotT2_MasterName",
        "ItemType": "Resource",
        "ItemTypeDisplayName": "@UI_ItemTypeDescription_Resource",
        "Description": "@IngotT2_Description",
        "ItemClass": [
          "Resource",
          "Ingot"
        ],
        "TradingCategory": "Resources",
        "TradingFamily": "RefinedResources",
        "TradingGroup": "Ingot",
        "BindOnPickup": 0,
        "NoBindOnPickupChance": 0,
        "BindOnEquip": 0,
        "GearScoreOverride": 0,
        "MinGearScore": 0,
        "MaxGearScore": 0,
        "Tier": 2,
        "ForceRarity": 0,
        "RequiredLevel": 0,
        "UseMaterialAffix": 1,
        "UiItemClass": "UI_Smelting",
        "IconPath": "lyshineui/images/icons/items/resource/ingott2.webp",
        "MaxStackSize": 10000,
        "IngredientCategories": [
          "MetalT2",
          "Metal"
        ],
        "IngredientBonusPrimary": 0,
        "IngredientBonusSecondary": 0,
        "IngredientGearScoreBaseBonus": 0,
        "IngredientGearScoreMaxBonus": 0,
        "Weight": 3,
        "NotDroppable": false
      },
      {
        "ItemID": "OreT1",
        "Name": "@OreT1_MasterName",
        "ItemType": "Resource",
        "ItemTypeDisplayName": "@UI_ItemTypeDescription_Resource",
        "Description": "@OreT1_Description",
        "ItemClass": [
          "Resource",
          "Ore"
        ],
        "TradingCategory": "Resources",
        "TradingFamily": "RawResources",
        "TradingGroup": "Ore",
        "BindOnPickup": 0,
        "NoBindOnPickupChance": 0,
        "BindOnEquip": 0,
        "GearScoreOverride": 0,
        "MinGearScore": 0,
        "MaxGearScore": 0,
        "Tier": 1,
        "ForceRarity": 0,
        "RequiredLevel": 0,
        "UseMaterialAffix": 1,
        "UiItemClass": "UI_Smelting",
        "IconPath": "lyshineui/images/icons/items/resource/oret1.webp",
        "MaxStackSize": 10000,
        "IngredientCategories": [
          "Ore"
        ],
        "IngredientBonusPrimary": 0,
        "IngredientBonusSecondary": 0,
        "IngredientGearScoreBaseBonus": 0,
        "IngredientGearScoreMaxBonus": 0,
        "Weight": 2,
        "NotDroppable": false
      },
      {
        "ItemID": "RubyT2",
        "Name": "@RubyT2_MasterName",
        "ItemType": "Resource",
        "ItemTypeDisplayName": "@ui_itemtypedescription_resource",
        "Description": "@RubyT2_Description",
        "ItemClass": [
          "Resource",
          "Gem"
        ],
        "TradingCategory": "Resources",
        "TradingFamily": "RawResources",
        "TradingGroup": "RawGem",
        "BindOnPickup": 0,
        "NoBindOnPickupChance": 0,
        "BindOnEquip": 0,
        "GearScoreOverride": 0,
        "MinGearScore": 0,
        "MaxGearScore": 0,
        "Tier": 3,
        "ForceRarity": 1,
        "RequiredLevel": 0,
        "UseMaterialAffix": 0,
        "UiItemClass": "UI_Jewelcrafting",
        "IconPath": "lyshineui/images/icons/items/resource/rubyt2.webp",
        "MaxStackSize": 10000,
        "IngredientCategories": [
          "Gemstone",
          "GemstoneT2"
        ],
        "IngredientBonusPrimary": 0,
        "IngredientBonusSecondary": 0,
        "IngredientGearScoreBaseBonus": 0,
        "IngredientGearScoreMaxBonus": 0,
        "Weight": 1,
        "NotDroppable": false
      },
      {
        "ItemID": "RubyT1",
        "Name": "@RubyT1_MasterName",
        "ItemType": "Resource",
        "ItemTypeDisplayName": "@ui_itemtypedescription_resource",
        "Description": "@RubyT1_Description",
        "ItemClass": [
          "Resource",
          "Gem"
        ],
        "TradingCategory": "Resources",
        "TradingFamily": "RawResources",
        "TradingGroup": "RawGem",
        "BindOnPickup": 0,
        "NoBindOnPickupChance": 0,
        "BindOnEquip": 0,
        "GearScoreOverride": 0,
        "MinGearScore": 0,
        "MaxGearScore": 0,
        "Tier": 2,
        "ForceRarity": 0,
        "RequiredLevel": 0,
        "UseMaterialAffix": 0,
        "UiItemClass": "UI_Jewelcrafting",
        "IconPath": "lyshineui/images/icons/items/resource/rubyt1.webp",
        "MaxStackSize": 10000,
        "IngredientCategories": [
          "Gemstone",
          "GemstoneT1"
        ],
        "IngredientBonusPrimary": 0,
        "IngredientBonusSecondary": 0,
        "IngredientGearScoreBaseBonus": 0,
        "IngredientGearScoreMaxBonus": 0,
        "Weight": 1,
        "NotDroppable": false
      },
      {
        "ItemID": "FluxT5",
        "Name": "@FluxT5_MasterName",
        "ItemType": "Resource",
        "ItemTypeDisplayName": "@UI_ItemTypeDescription_Resource",
        "Description": "@FluxT5_Description",
        "ItemClass": [
          "Resource"
        ],
        "TradingCategory": "Resources",
        "TradingFamily": "Components",
        "TradingGroup": "RefiningComponents",
        "BindOnPickup": 0,
        "NoBindOnPickupChance": 0,
        "BindOnEquip": 0,
        "GearScoreOverride": 0,
        "MinGearScore": 0,
        "MaxGearScore": 0,
        "Tier": 5,
        "ForceRarity": 1,
        "RequiredLevel": 0,
        "UseMaterialAffix": 1,
        "UiItemClass": "UI_Refining",
        "IconPath": "lyshineui/images/icons/items/resource/fluxt5.webp",
        "MaxStackSize": 10000,
        "IngredientCategories": [
          "Flux",
          "SandpaperReagentsT5",
          "TanninReagentsT5",
          "SolventReagentsT5",
          "ClothWeaveReagentsT5"
        ],
        "IngredientBonusPrimary": 0,
        "IngredientBonusSecondary": 0,
        "IngredientGearScoreBaseBonus": 0,
        "IngredientGearScoreMaxBonus": 0,
        "Weight": 1,
        "NotDroppable": false
      },
      {
        "ItemID": "SandpaperT5",
        "Name": "@SandpaperT5_MasterName",
        "ItemType": "Resource",
        "ItemTypeDisplayName": "@UI_ItemTypeDescription_Resource",
        "Description": "@SandpaperT5_Description",
        "ItemClass": [
          "Resource"
        ],
        "TradingCategory": "Resources",
        "TradingFamily": "Components",
        "TradingGroup": "RefiningComponents",
        "BindOnPickup": 0,
        "NoBindOnPickupChance": 0,
        "BindOnEquip": 0,
        "GearScoreOverride": 0,
        "MinGearScore": 0,
        "MaxGearScore": 0,
        "Tier": 5,
        "ForceRarity": 1,
        "RequiredLevel": 0,
        "UseMaterialAffix": 0,
        "UiItemClass": "UI_Refining",
        "IconPath": "lyshineui/images/icons/items/resource/sandpapert5.webp",
        "MaxStackSize": 10000,
        "IngredientCategories": [
          "Sandpaper",
          "FluxReagentsT5",
          "TanninReagentsT5",
          "SolventReagentsT5",
          "ClothWeaveReagentsT5"
        ],
        "IngredientBonusPrimary": 0,
        "IngredientBonusSecondary": 0,
        "IngredientGearScoreBaseBonus": 0,
        "IngredientGearScoreMaxBonus": 0,
        "Weight": 1,
        "NotDroppable": false
      },
      {
        "ItemID": "TanninT5",
        "Name": "@TanninT5_MasterName",
        "ItemType": "Resource",
        "ItemTypeDisplayName": "@UI_ItemTypeDescription_Resource",
        "Description": "@TanninT5_Description",
        "ItemClass": [
          "Resource"
        ],
        "TradingCategory": "Resources",
        "TradingFamily": "Components",
        "TradingGroup": "RefiningComponents",
        "BindOnPickup": 0,
        "NoBindOnPickupChance": 0,
        "BindOnEquip": 0,
        "GearScoreOverride": 0,
        "MinGearScore": 0,
        "MaxGearScore": 0,
        "Tier": 5,
        "ForceRarity": 1,
        "RequiredLevel": 0,
        "UseMaterialAffix": 0,
        "UiItemClass": "UI_Refining",
        "IconPath": "lyshineui/images/icons/items/resource/tannint5.webp",
        "MaxStackSize": 10000,
        "IngredientCategories": [
          "Tannin",
          "FluxReagentsT5",
          "SandpaperReagentsT5",
          "SolventReagentsT5",
          "ClothWeaveReagentsT5"
        ],
        "IngredientBonusPrimary": 0,
        "IngredientBonusSecondary": 0,
        "IngredientGearScoreBaseBonus": 0,
        "IngredientGearScoreMaxBonus": 0,
        "Weight": 1,
        "NotDroppable": false
      },
      {
        "ItemID": "SolventT5",
        "Name": "@SolventT5_MasterName",
        "ItemType": "Resource",
        "ItemTypeDisplayName": "@UI_ItemTypeDescription_Resource",
        "Description": "@SolventT5_Description",
        "ItemClass": [
          "Resource"
        ],
        "TradingCategory": "Resources",
        "TradingFamily": "Components",
        "TradingGroup": "RefiningComponents",
        "BindOnPickup": 0,
        "NoBindOnPickupChance": 0,
        "BindOnEquip": 0,
        "GearScoreOverride": 0,
        "MinGearScore": 0,
        "MaxGearScore": 0,
        "Tier": 5,
        "ForceRarity": 1,
        "RequiredLevel": 0,
        "UseMaterialAffix": 0,
        "UiItemClass": "UI_Refining",
        "IconPath": "lyshineui/images/icons/items/resource/solventt5.webp",
        "MaxStackSize": 10000,
        "IngredientCategories": [
          "Solvent",
          "FluxReagentsT5",
          "SandpaperReagentsT5",
          "TanninReagentsT5",
          "ClothWeaveReagentsT5"
        ],
        "IngredientBonusPrimary": 0,
        "IngredientBonusSecondary": 0,
        "IngredientGearScoreBaseBonus": 0,
        "IngredientGearScoreMaxBonus": 0,
        "Weight": 1,
        "NotDroppable": false
      },
      {
        "ItemID": "ClothWeaveT5",
        "Name": "@ClothWeaveT5_MasterName",
        "ItemType": "Resource",
        "ItemTypeDisplayName": "@UI_ItemTypeDescription_Resource",
        "Description": "@ClothWeaveT5_Description",
        "ItemClass": [
          "Resource"
        ],
        "TradingCategory": "Resources",
        "TradingFamily": "Components",
        "TradingGroup": "RefiningComponents",
        "BindOnPickup": 0,
        "NoBindOnPickupChance": 0,
        "BindOnEquip": 0,
        "GearScoreOverride": 0,
        "MinGearScore": 0,
        "MaxGearScore": 0,
        "Tier": 5,
        "ForceRarity": 1,
        "RequiredLevel": 0,
        "UseMaterialAffix": 1,
        "UiItemClass": "UI_Refining",
        "IconPath": "lyshineui/images/icons/items/resource/clothweavet5.webp",
        "MaxStackSize": 10000,
        "IngredientCategories": [
          "Crossweave",
          "FluxReagentsT5",
          "SandpaperReagentsT5",
          "TanninReagentsT5",
          "SolventReagentsT5"
        ],
        "IngredientBonusPrimary": 0,
        "IngredientBonusSecondary": 0,
        "IngredientGearScoreBaseBonus": 0,
        "IngredientGearScoreMaxBonus": 0,
        "Weight": 1,
        "NotDroppable": false
      },
      {
        "ItemID": "ReagentConverterT5",
        "Name": "@ReagentConverterT5_MasterName",
        "ItemType": "Resource",
        "ItemTypeDisplayName": "@UI_ItemTypeDescription_Resource",
        "Description": "@ReagentConverterT5_Description",
        "ItemClass": [
          "Resource"
        ],
        "TradingCategory": "Resources",
        "TradingFamily": "Components",
        "TradingGroup": "CraftingComponents",
        "BindOnPickup": 0,
        "NoBindOnPickupChance": 0,
        "BindOnEquip": 0,
        "GearScoreOverride": 0,
        "MinGearScore": 0,
        "MaxGearScore": 0,
        "Tier": 5,
        "ForceRarity": 2,
        "RequiredLevel": 0,
        "UseMaterialAffix": 0,
        "UiItemClass": "UI_Material",
        "IconPath": "lyshineui/images/icons/items/resource/arcanereactort5.webp",
        "MaxStackSize": 10000,
        "IngredientBonusPrimary": 0,
        "IngredientBonusSecondary": 0,
        "IngredientGearScoreBaseBonus": 0,
        "IngredientGearScoreMaxBonus": 0,
        "Weight": 1,
        "NotDroppable": false
      },
      {
        "ItemID": "CharcoalT1",
        "Name": "@CharcoalT1_MasterName",
        "ItemType": "Resource",
        "ItemTypeDisplayName": "@UI_ItemTypeDescription_Resource",
        "Description": "@CharcoalT1_Description",
        "ItemClass": [
          "Resource"
        ],
        "TradingCategory": "Resources",
        "TradingFamily": "RefinedResources",
        "TradingGroup": "Charcoal",
        "BindOnPickup": 0,
        "NoBindOnPickupChance": 0,
        "BindOnEquip": 0,
        "GearScoreOverride": 0,
        "MinGearScore": 0,
        "MaxGearScore": 0,
        "Tier": 2,
        "ForceRarity": 0,
        "RequiredLevel": 0,
        "UseMaterialAffix": 0,
        "UiItemClass": "UI_Smelting",
        "IconPath": "lyshineui/images/icons/items/resource/charcoalt1.webp",
        "MaxStackSize": 10000,
        "IngredientBonusPrimary": 0,
        "IngredientBonusSecondary": 0,
        "IngredientGearScoreBaseBonus": 0,
        "IngredientGearScoreMaxBonus": 0,
        "Weight": 1,
        "NotDroppable": false
      },
      {
        "ItemID": "WoodenCoin",
        "Name": "@WoodenCoin_MasterName",
        "ItemType": "Resource",
        "ItemTypeDisplayName": "@UI_ItemTypeDescription_Resource",
        "Description": "@WoodenCoin_Description",
        "ItemClass": [
          "Resource"
        ],
        "TradingCategory": "Resources",
        "TradingFamily": "Components",
        "TradingGroup": "CraftingComponents",
        "BindOnPickup": 0,
        "NoBindOnPickupChance": 0,
        "BindOnEquip": 0,
        "GearScoreOverride": 0,
        "MinGearScore": 0,
        "MaxGearScore": 0,
        "Tier": 0,
        "ForceRarity": 1,
        "RequiredLevel": 0,
        "UseMaterialAffix": 0,
        "UiItemClass": "UI_Material",
        "IconPath": "lyshineui/images/icons/items/resource/mi_largegoldcoin.webp",
        "MaxStackSize": 10000,
        "IngredientBonusPrimary": 0,
        "IngredientBonusSecondary": 0,
        "IngredientGearScoreBaseBonus": 0,
        "IngredientGearScoreMaxBonus": 0,
        "Weight": 1,
        "NotDroppable": false
      },
      {
        "ItemID": "BeeswaxT1",
        "Name": "@BeeswaxT1_MasterName",
        "ItemType": "Resource",
        "ItemTypeDisplayName": "@UI_ItemTypeDescription_Resource",
        "Description": "@BeeswaxT1_Description",
        "ItemClass": [
          "Resource"
        ],
        "TradingCategory": "Resources",
        "TradingFamily": "RawResources",
        "TradingGroup": "Beeswax",
        "BindOnPickup": 0,
        "NoBindOnPickupChance": 0,
        "BindOnEquip": 0,
        "GearScoreOverride": 0,
        "MinGearScore": 0,
        "MaxGearScore": 0,
        "Tier": 0,
        "ForceRarity": 0,
        "RequiredLevel": 0,
        "UseMaterialAffix": 0,
        "UiItemClass": "UI_Material",
        "IconPath": "lyshineui/images/icons/items/resource/beeswaxt1.webp",
        "MaxStackSize": 10000,
        "IngredientBonusPrimary": 0,
        "IngredientBonusSecondary": 0,
        "IngredientGearScoreBaseBonus": 0,
        "IngredientGearScoreMaxBonus": 0,
        "Weight": 1,
        "NotDroppable": false
      },
      {
        "ItemID": "AlchemyFireT2",
        "Name": "@AlchemyFireT2_MasterName",
        "ItemType": "Resource",
        "ItemTypeDisplayName": "@ui_itemtypedescription_resource",
        "Description": "@AlchemyFireT2_Description",
        "ItemClass": [
          "Resource",
          "Alchemy"
        ],
        "TradingCategory": "Resources",
        "TradingFamily": "ArcanaResources",
        "TradingGroup": "ArcanaFire",
        "BindOnPickup": 0,
        "NoBindOnPickupChance": 0,
        "BindOnEquip": 0,
        "GearScoreOverride": 0,
        "MinGearScore": 0,
        "MaxGearScore": 0,
        "Tier": 3,
        "ForceRarity": 1,
        "RequiredLevel": 0,
        "UseMaterialAffix": 0,
        "UiItemClass": "UI_Alchemy",
        "IconPath": "lyshineui/images/icons/items/resource/alchemyfiret2.webp",
        "MaxStackSize": 10000,
        "IngredientCategories": [
          "AlchemyFire",
          "ArcanaFire",
          "AlchemyFireT3",
          "ArcanaFireT3"
        ],
        "IngredientBonusPrimary": 0,
        "IngredientBonusSecondary": 0,
        "IngredientGearScoreBaseBonus": 0,
        "IngredientGearScoreMaxBonus": 0,
        "Weight": 1,
        "NotDroppable": false
      },
      {
        "ItemID": "AlchemyFireT1",
        "Name": "@AlchemyFireT1_MasterName",
        "ItemType": "Resource",
        "ItemTypeDisplayName": "@UI_ItemTypeDescription_Resource",
        "Description": "@AlchemyFireT1_Description",
        "ItemClass": [
          "Resource",
          "Alchemy"
        ],
        "TradingCategory": "Resources",
        "TradingFamily": "ArcanaResources",
        "TradingGroup": "ArcanaFire",
        "BindOnPickup": 0,
        "NoBindOnPickupChance": 0,
        "BindOnEquip": 0,
        "GearScoreOverride": 0,
        "MinGearScore": 0,
        "MaxGearScore": 0,
        "Tier": 2,
        "ForceRarity": 0,
        "RequiredLevel": 0,
        "UseMaterialAffix": 0,
        "UiItemClass": "UI_Alchemy",
        "IconPath": "lyshineui/images/icons/items/resource/alchemyfiret1.webp",
        "MaxStackSize": 10000,
        "IngredientCategories": [
          "AlchemyFire",
          "ArcanaFire",
          "AlchemyFireT2",
          "ArcanaFireT2",
          "AlchemyProtectiveT2"
        ],
        "IngredientBonusPrimary": 0,
        "IngredientBonusSecondary": 0,
        "IngredientGearScoreBaseBonus": 0,
        "IngredientGearScoreMaxBonus": 0,
        "Weight": 1,
        "NotDroppable": false
      }
    ] satisfies Partial<MasterItemDefinitionsTestData>[],
    [DATASHEETS.HouseItems.HouseItems.uri]: [
      {
        "HouseItemID": "House_HousingItem_Lighting_CandleHolder_A",
        "UIHousingCategory": "Lighting",
        "HousingTag1 Placed": [
          "OnFurniture"
        ],
        "HousingTag2 Points": [
          "IsLighting"
        ],
        "HousingTag3 Limiter": [
          "LimiterLighting"
        ],
        "HousingTags": [
          "OnFurniture",
          "IsLighting",
          "LimiterLighting"
        ],
        "ItemRarity": "Uncommon",
        "ForceRarity": 1,
        "StorageBonus": 0,
        "Name": "@House_HousingItem_Lighting_CandleHolder_A_MasterName",
        "Description": "@House_HousingItem_Lighting_CandleHolder_A_Description",
        "IconPath": "lyshineui/images/icons/items/housingitem/house_housingitem_lighting_candleholder_a.webp",
        "Weight": 7,
        "TradingCategory": "Furnishings",
        "TradingFamily": "HousingTrdF_Decorations",
        "TradingGroup": "HousingTrdG_Lighting",
        "ItemType": "HousingItem",
        "UiItemClass": "UI_Furniture",
        "Tier": 2,
        "BindOnPickup": false,
        "MaxStackSize": 4,
        "ItemTypeDisplayName": "@UI_ItemTypeDescription_HousingItem"
      }
    ] satisfies Partial<HouseItemsTestData>[],
    [DATASHEETS.CraftingRecipeData.CraftingRecipes.uri]: [
      {
        "RecipeID": "IngotT52",
        "CraftingCategory": "RefinedResources",
        "CraftingGroup": "Metal",
        "AdditionalFilterText": "@Metal_CategoryName",
        "CraftAll": true,
        "IsRefining": true,
        "CraftingFee": 22,
        "UseCraftingTax": 0,
        "Tradeskill": "Smelting",
        "RecipeLevel": 205,
        "StationType1": "smelting2",
        "OutputQty": 1,
        "ItemID": "IngotT52",
        "SkipGrantItems": false,
        "BaseGearScore": 0,
        "BaseTier": 5,
        "Ingredient1": "OreT52",
        "Type1": "Item",
        "Ingredient2": "IngotT5",
        "Type2": "Item",
        "Ingredient3": "FluxT5",
        "Type3": "Item",
        "Ingredient4": "CharcoalT1",
        "Type4": "Item",
        "Qty1": 12,
        "Qty2": 2,
        "Qty3": 1,
        "Qty4": 2,
        "CooldownSeconds": 0,
        "CooldownQuantity": 0,
        "BonusItemChance": -0.2,
        "BonusItemChanceIncrease": "0.25,0.5,0.75,1",
        "BonusItemChanceDecrease": "-0.05,-0.1,-0.15,-0.2,-0.25",
        "PerkCost": 0
      },
      {
        "RecipeID": "IngotT5",
        "CraftingCategory": "RefinedResources",
        "CraftingGroup": "Metal",
        "AdditionalFilterText": "@Metal_CategoryName",
        "CraftAll": true,
        "IsRefining": true,
        "CraftingFee": 13,
        "UseCraftingTax": 0,
        "Tradeskill": "Smelting",
        "RecipeLevel": 150,
        "StationType1": "smelting2",
        "OutputQty": 1,
        "ItemID": "IngotT5",
        "SkipGrantItems": false,
        "BaseTier": 0,
        "Ingredient1": "OreT5",
        "Type1": "Item",
        "Ingredient2": "IngotT4",
        "Type2": "Item",
        "Ingredient3": "FluxT5",
        "Type3": "Item",
        "Ingredient4": "CharcoalT1",
        "Type4": "Item",
        "Qty1": 8,
        "Qty2": 2,
        "Qty3": 1,
        "Qty4": 2,
        "CooldownSeconds": 0,
        "CooldownQuantity": 0,
        "BonusItemChance": -0.07,
        "BonusItemChanceIncrease": "0.25,0.5,0.75,1",
        "BonusItemChanceDecrease": "-0.05,-0.1,-0.15,-0.2,-0.25"
      },
      {
        "RecipeID": "IngotT4",
        "CraftingCategory": "RefinedResources",
        "CraftingGroup": "Metal",
        "AdditionalFilterText": "@Metal_CategoryName",
        "CraftAll": true,
        "IsRefining": true,
        "CraftingFee": 7,
        "UseCraftingTax": 0,
        "Tradeskill": "Smelting",
        "RecipeLevel": 100,
        "StationType1": "smelting2",
        "OutputQty": 1,
        "ItemID": "IngotT4",
        "SkipGrantItems": false,
        "BaseTier": 0,
        "Ingredient1": "OreT4",
        "Type1": "Item",
        "Ingredient2": "IngotT3",
        "Type2": "Item",
        "Ingredient3": "FluxT5",
        "Type3": "Item",
        "Ingredient4": "CharcoalT1",
        "Type4": "Item",
        "Qty1": 6,
        "Qty2": 2,
        "Qty3": 1,
        "Qty4": 2,
        "CooldownSeconds": 0,
        "CooldownQuantity": 0,
        "BonusItemChance": -0.05,
        "BonusItemChanceIncrease": "0.25,0.5,0.75,1",
        "BonusItemChanceDecrease": "-0.05,-0.1,-0.15,-0.2,-0.25"
      },
      {
        "RecipeID": "IngotT3",
        "CraftingCategory": "RefinedResources",
        "CraftingGroup": "Metal",
        "AdditionalFilterText": "@Metal_CategoryName",
        "CraftAll": true,
        "IsRefining": true,
        "CraftingFee": 4,
        "UseCraftingTax": 0,
        "Tradeskill": "Smelting",
        "RecipeLevel": 50,
        "StationType1": "smelting2",
        "OutputQty": 1,
        "ItemID": "IngotT3",
        "SkipGrantItems": false,
        "BaseTier": 0,
        "Ingredient1": "IngotT2",
        "Type1": "Item",
        "Ingredient2": "FluxT5",
        "Type2": "Item",
        "Ingredient3": "CharcoalT1",
        "Type3": "Item",
        "Qty1": 3,
        "Qty2": 1,
        "Qty3": 2,
        "CooldownSeconds": 0,
        "CooldownQuantity": 0,
        "BonusItemChance": -0.02,
        "BonusItemChanceIncrease": "0,0.5,0.75,1",
        "BonusItemChanceDecrease": "-0.05,-0.1,-0.15,-0.2,-0.25"
      },
      {
        "RecipeID": "IngotT2",
        "CraftingCategory": "RefinedResources",
        "CraftingGroup": "Metal",
        "AdditionalFilterText": "@Metal_CategoryName",
        "CraftAll": true,
        "IsRefining": true,
        "CraftingFee": 1,
        "UseCraftingTax": 0,
        "Tradeskill": "Smelting",
        "RecipeLevel": 0,
        "StationType1": "smelting2",
        "OutputQty": 1,
        "ItemID": "IngotT2",
        "SkipGrantItems": false,
        "BaseTier": 0,
        "Ingredient1": "OreT1",
        "Type1": "Item",
        "Qty1": 4,
        "Qty2": 1,
        "CooldownSeconds": 0,
        "CooldownQuantity": 0,
        "BonusItemChance": 0,
        "BonusItemChanceIncrease": "0.25,0.5,0.75,1",
        "BonusItemChanceDecrease": "-0.05,-0.1,-0.15,-0.2,-0.25"
      },
      {
        "RecipeID": "RubyT2Fuse",
        "CraftingCategory": "FuseGems",
        "CraftingGroup": "CutGemsFuseT2",
        "AdditionalFilterText": "@ui_gemsocket",
        "CraftAll": true,
        "IsRefining": true,
        "CraftingFee": 12,
        "UseCraftingTax": 0,
        "Tradeskill": "Jewelcrafting",
        "RecipeLevel": 50,
        "StationType1": "outfitting2",
        "OutputQty": 1,
        "ItemID": "RubyT2",
        "SkipGrantItems": false,
        "BaseGearScore": 0,
        "BaseTier": 0,
        "Ingredient1": "RubyT1",
        "Type1": "Item",
        "Ingredient2": "AlchemyFireT2",
        "Type2": "Item",
        "Ingredient3": "Solvent",
        "Type3": "Category_Only",
        "Qty1": 3,
        "Qty2": 1,
        "Qty3": 2,
        "Qty4": 0,
        "Qty5": 0,
        "Qty6": 0,
        "Qty7": 0,
        "BonusItemChance": 0,
        "PerkCost": 0
      },
      {
        "RecipeID": "AlchemyFireT2",
        "CraftingCategory": "ArcanaRefining",
        "CraftingGroup": "ElementalWisp",
        "CraftAll": true,
        "IsRefining": true,
        "CraftingFee": 15,
        "UseCraftingTax": 1,
        "Tradeskill": "Arcana",
        "RecipeLevel": 25,
        "StationType1": "alchemy2",
        "OutputQty": 1,
        "ItemID": "AlchemyFireT2",
        "SkipGrantItems": false,
        "BaseGearScore": 0,
        "BaseTier": 0,
        "Ingredient1": "AlchemyFireT1",
        "Type1": "Item",
        "Qty1": 5,
        "Qty2": 0,
        "Qty3": 0,
        "Qty4": 0,
        "Qty5": 0,
        "Qty6": 0,
        "Qty7": 0,
        "CooldownSeconds": 0,
        "CooldownQuantity": 0,
        "BonusItemChance": 0,
        "PerkCost": 0
      },
      {
        "RecipeID": "Smelter_SandpaperT5",
        "CraftingCategory": "MaterialConversion",
        "CraftingGroup": "Conversion3",
        "DisplayIngredients": "ReagentConverterT5",
        "CraftAll": true,
        "IsRefining": true,
        "CraftingFee": 100,
        "UseCraftingTax": 0,
        "Tradeskill": "Smelting",
        "RecipeLevel": 0,
        "StationType1": "smelting2",
        "OutputQty": 15,
        "ItemID": "SandpaperT5",
        "SkipGrantItems": false,
        "BaseTier": 0,
        "Ingredient1": "ReagentConverterT5",
        "Type1": "Item",
        "Ingredient2": "SandpaperReagentsT5",
        "Type2": "Category_Only",
        "Qty1": 1,
        "Qty2": 20,
        "Qty3": 0,
        "Qty4": 0,
        "Qty5": 0,
        "CooldownSeconds": 0,
        "CooldownQuantity": 0,
        "BonusItemChance": -0.3,
        "BonusItemChanceIncrease": "0,0,0,0,0",
        "BonusItemChanceDecrease": "0,0,0,0,0"
      },
      {
        "RecipeID": "Smelter_FluxT5",
        "CraftingCategory": "MaterialConversion",
        "CraftingGroup": "Conversion3",
        "DisplayIngredients": "ReagentConverterT5",
        "CraftAll": true,
        "IsRefining": true,
        "CraftingFee": 100,
        "UseCraftingTax": 0,
        "Tradeskill": "Smelting",
        "RecipeLevel": 0,
        "StationType1": "smelting2",
        "OutputQty": 15,
        "ItemID": "FluxT5",
        "SkipGrantItems": false,
        "BaseTier": 0,
        "Ingredient1": "ReagentConverterT5",
        "Type1": "Item",
        "Ingredient2": "FluxReagentsT5",
        "Type2": "Category_Only",
        "Qty1": 1,
        "Qty2": 20,
        "Qty3": 0,
        "Qty4": 0,
        "Qty5": 0,
        "CooldownSeconds": 0,
        "CooldownQuantity": 0,
        "BonusItemChance": -0.3,
        "BonusItemChanceIncrease": "0,0,0,0,0",
        "BonusItemChanceDecrease": "0,0,0,0,0"
      },
      {
        "RecipeID": "Smelter_ClothWeaveT5",
        "CraftingCategory": "MaterialConversion",
        "CraftingGroup": "Conversion3",
        "DisplayIngredients": "ReagentConverterT5",
        "CraftAll": true,
        "IsRefining": true,
        "CraftingFee": 100,
        "UseCraftingTax": 0,
        "Tradeskill": "Smelting",
        "RecipeLevel": 0,
        "StationType1": "smelting2",
        "OutputQty": 15,
        "ItemID": "ClothWeaveT5",
        "SkipGrantItems": false,
        "BaseTier": 0,
        "Ingredient1": "ReagentConverterT5",
        "Type1": "Item",
        "Ingredient2": "ClothWeaveReagentsT5",
        "Type2": "Category_Only",
        "Qty1": 1,
        "Qty2": 20,
        "Qty3": 0,
        "Qty4": 0,
        "Qty5": 0,
        "CooldownSeconds": 0,
        "CooldownQuantity": 0,
        "BonusItemChance": -0.3,
        "BonusItemChanceIncrease": "0,0,0,0,0",
        "BonusItemChanceDecrease": "0,0,0,0,0"
      },
      {
        "RecipeID": "Smelter_SolventT5",
        "CraftingCategory": "MaterialConversion",
        "CraftingGroup": "Conversion3",
        "DisplayIngredients": "ReagentConverterT5",
        "CraftAll": true,
        "IsRefining": true,
        "CraftingFee": 100,
        "UseCraftingTax": 0,
        "Tradeskill": "Smelting",
        "RecipeLevel": 0,
        "StationType1": "smelting2",
        "OutputQty": 15,
        "ItemID": "SolventT5",
        "SkipGrantItems": false,
        "BaseTier": 0,
        "Ingredient1": "ReagentConverterT5",
        "Type1": "Item",
        "Ingredient2": "SolventReagentsT5",
        "Type2": "Category_Only",
        "Qty1": 1,
        "Qty2": 20,
        "Qty3": 0,
        "Qty4": 0,
        "Qty5": 0,
        "CooldownSeconds": 0,
        "CooldownQuantity": 0,
        "BonusItemChance": -0.3,
        "BonusItemChanceIncrease": "0,0,0,0,0",
        "BonusItemChanceDecrease": "0,0,0,0,0"
      },
      {
        "RecipeID": "Smelter_TanninT5",
        "CraftingCategory": "MaterialConversion",
        "CraftingGroup": "Conversion3",
        "DisplayIngredients": "ReagentConverterT5",
        "CraftAll": true,
        "IsRefining": true,
        "CraftingFee": 100,
        "UseCraftingTax": 0,
        "Tradeskill": "Smelting",
        "RecipeLevel": 0,
        "StationType1": "smelting2",
        "OutputQty": 15,
        "ItemID": "TanninT5",
        "SkipGrantItems": false,
        "BaseTier": 0,
        "Ingredient1": "ReagentConverterT5",
        "Type1": "Item",
        "Ingredient2": "TanninReagentsT5",
        "Type2": "Category_Only",
        "Qty1": 1,
        "Qty2": 20,
        "Qty3": 0,
        "Qty4": 0,
        "Qty5": 0,
        "CooldownSeconds": 0,
        "CooldownQuantity": 0,
        "BonusItemChance": -0.3,
        "BonusItemChanceIncrease": "0,0,0,0,0",
        "BonusItemChanceDecrease": "0,0,0,0,0"
      },
      {
        "RecipeID": "Stonecutter_SandpaperT5",
        "CraftingCategory": "MaterialConversion",
        "CraftingGroup": "Conversion3",
        "DisplayIngredients": "ReagentConverterT5",
        "CraftAll": true,
        "IsRefining": true,
        "CraftingFee": 100,
        "UseCraftingTax": 0,
        "Tradeskill": "Stonecutting",
        "RecipeLevel": 0,
        "StationType1": "masonry2",
        "OutputQty": 15,
        "ItemID": "SandpaperT5",
        "SkipGrantItems": false,
        "BaseTier": 0,
        "Ingredient1": "ReagentConverterT5",
        "Type1": "Item",
        "Ingredient2": "SandpaperReagentsT5",
        "Type2": "Category_Only",
        "Qty1": 1,
        "Qty2": 20,
        "Qty3": 0,
        "Qty4": 0,
        "Qty5": 0,
        "CooldownSeconds": 0,
        "CooldownQuantity": 0,
        "BonusItemChance": -0.3,
        "BonusItemChanceIncrease": "0,0,0,0,0",
        "BonusItemChanceDecrease": "0,0,0,0,0"
      },
      {
        "RecipeID": "Stonecutter_FluxT5",
        "CraftingCategory": "MaterialConversion",
        "CraftingGroup": "Conversion3",
        "DisplayIngredients": "ReagentConverterT5",
        "CraftAll": true,
        "IsRefining": true,
        "CraftingFee": 100,
        "UseCraftingTax": 0,
        "Tradeskill": "Stonecutting",
        "RecipeLevel": 0,
        "StationType1": "masonry2",
        "OutputQty": 15,
        "ItemID": "FluxT5",
        "SkipGrantItems": false,
        "BaseTier": 0,
        "Ingredient1": "ReagentConverterT5",
        "Type1": "Item",
        "Ingredient2": "FluxReagentsT5",
        "Type2": "Category_Only",
        "Qty1": 1,
        "Qty2": 20,
        "Qty3": 0,
        "Qty4": 0,
        "Qty5": 0,
        "CooldownSeconds": 0,
        "CooldownQuantity": 0,
        "BonusItemChance": -0.3,
        "BonusItemChanceIncrease": "0,0,0,0,0",
        "BonusItemChanceDecrease": "0,0,0,0,0"
      },
      {
        "RecipeID": "Stonecutter_ClothWeaveT5",
        "CraftingCategory": "MaterialConversion",
        "CraftingGroup": "Conversion3",
        "DisplayIngredients": "ReagentConverterT5",
        "CraftAll": true,
        "IsRefining": true,
        "CraftingFee": 100,
        "UseCraftingTax": 0,
        "Tradeskill": "Stonecutting",
        "RecipeLevel": 0,
        "StationType1": "masonry2",
        "OutputQty": 15,
        "ItemID": "ClothWeaveT5",
        "SkipGrantItems": false,
        "BaseTier": 0,
        "Ingredient1": "ReagentConverterT5",
        "Type1": "Item",
        "Ingredient2": "ClothWeaveReagentsT5",
        "Type2": "Category_Only",
        "Qty1": 1,
        "Qty2": 20,
        "Qty3": 0,
        "Qty4": 0,
        "Qty5": 0,
        "CooldownSeconds": 0,
        "CooldownQuantity": 0,
        "BonusItemChance": -0.3,
        "BonusItemChanceIncrease": "0,0,0,0,0",
        "BonusItemChanceDecrease": "0,0,0,0,0"
      },
      {
        "RecipeID": "Stonecutter_SolventT5",
        "CraftingCategory": "MaterialConversion",
        "CraftingGroup": "Conversion3",
        "DisplayIngredients": "ReagentConverterT5",
        "CraftAll": true,
        "IsRefining": true,
        "CraftingFee": 100,
        "UseCraftingTax": 0,
        "Tradeskill": "Stonecutting",
        "RecipeLevel": 0,
        "StationType1": "masonry2",
        "OutputQty": 15,
        "ItemID": "SolventT5",
        "SkipGrantItems": false,
        "BaseTier": 0,
        "Ingredient1": "ReagentConverterT5",
        "Type1": "Item",
        "Ingredient2": "SolventReagentsT5",
        "Type2": "Category_Only",
        "Qty1": 1,
        "Qty2": 20,
        "Qty3": 0,
        "Qty4": 0,
        "Qty5": 0,
        "CooldownSeconds": 0,
        "CooldownQuantity": 0,
        "BonusItemChance": -0.3,
        "BonusItemChanceIncrease": "0,0,0,0,0",
        "BonusItemChanceDecrease": "0,0,0,0,0"
      },
      {
        "RecipeID": "Stonecutter_TanninT5",
        "CraftingCategory": "MaterialConversion",
        "CraftingGroup": "Conversion3",
        "DisplayIngredients": "ReagentConverterT5",
        "CraftAll": true,
        "IsRefining": true,
        "CraftingFee": 100,
        "UseCraftingTax": 0,
        "Tradeskill": "Stonecutting",
        "RecipeLevel": 0,
        "StationType1": "masonry2",
        "OutputQty": 15,
        "ItemID": "TanninT5",
        "SkipGrantItems": false,
        "BaseTier": 0,
        "Ingredient1": "ReagentConverterT5",
        "Type1": "Item",
        "Ingredient2": "TanninReagentsT5",
        "Type2": "Category_Only",
        "Qty1": 1,
        "Qty2": 20,
        "Qty3": 0,
        "Qty4": 0,
        "Qty5": 0,
        "CooldownSeconds": 0,
        "CooldownQuantity": 0,
        "BonusItemChance": -0.3,
        "BonusItemChanceIncrease": "0,0,0,0,0",
        "BonusItemChanceDecrease": "0,0,0,0,0"
      },
      {
        "RecipeID": "Loom_SandpaperT5",
        "CraftingCategory": "MaterialConversion",
        "CraftingGroup": "Conversion3",
        "DisplayIngredients": "ReagentConverterT5",
        "CraftAll": true,
        "IsRefining": true,
        "CraftingFee": 100,
        "UseCraftingTax": 0,
        "Tradeskill": "Weaving",
        "RecipeLevel": 0,
        "StationType1": "weaving2",
        "OutputQty": 15,
        "ItemID": "SandpaperT5",
        "SkipGrantItems": false,
        "BaseTier": 0,
        "Ingredient1": "ReagentConverterT5",
        "Type1": "Item",
        "Ingredient2": "SandpaperReagentsT5",
        "Type2": "Category_Only",
        "Qty1": 1,
        "Qty2": 20,
        "Qty3": 0,
        "Qty4": 0,
        "Qty5": 0,
        "CooldownSeconds": 0,
        "CooldownQuantity": 0,
        "BonusItemChance": -0.3,
        "BonusItemChanceIncrease": "0,0,0,0,0",
        "BonusItemChanceDecrease": "0,0,0,0,0"
      },
      {
        "RecipeID": "Loom_FluxT5",
        "CraftingCategory": "MaterialConversion",
        "CraftingGroup": "Conversion3",
        "DisplayIngredients": "ReagentConverterT5",
        "CraftAll": true,
        "IsRefining": true,
        "CraftingFee": 100,
        "UseCraftingTax": 0,
        "Tradeskill": "Weaving",
        "RecipeLevel": 0,
        "StationType1": "weaving2",
        "OutputQty": 15,
        "ItemID": "FluxT5",
        "SkipGrantItems": false,
        "BaseTier": 0,
        "Ingredient1": "ReagentConverterT5",
        "Type1": "Item",
        "Ingredient2": "FluxReagentsT5",
        "Type2": "Category_Only",
        "Qty1": 1,
        "Qty2": 20,
        "Qty3": 0,
        "Qty4": 0,
        "Qty5": 0,
        "CooldownSeconds": 0,
        "CooldownQuantity": 0,
        "BonusItemChance": -0.3,
        "BonusItemChanceIncrease": "0,0,0,0,0",
        "BonusItemChanceDecrease": "0,0,0,0,0"
      },
      {
        "RecipeID": "Loom_ClothWeaveT5",
        "CraftingCategory": "MaterialConversion",
        "CraftingGroup": "Conversion3",
        "DisplayIngredients": "ReagentConverterT5",
        "CraftAll": true,
        "IsRefining": true,
        "CraftingFee": 100,
        "UseCraftingTax": 0,
        "Tradeskill": "Weaving",
        "RecipeLevel": 0,
        "StationType1": "weaving2",
        "OutputQty": 15,
        "ItemID": "ClothWeaveT5",
        "SkipGrantItems": false,
        "BaseTier": 0,
        "Ingredient1": "ReagentConverterT5",
        "Type1": "Item",
        "Ingredient2": "ClothWeaveReagentsT5",
        "Type2": "Category_Only",
        "Qty1": 1,
        "Qty2": 20,
        "Qty3": 0,
        "Qty4": 0,
        "Qty5": 0,
        "CooldownSeconds": 0,
        "CooldownQuantity": 0,
        "BonusItemChance": -0.3,
        "BonusItemChanceIncrease": "0,0,0,0,0",
        "BonusItemChanceDecrease": "0,0,0,0,0"
      },
      {
        "RecipeID": "Loom_SolventT5",
        "CraftingCategory": "MaterialConversion",
        "CraftingGroup": "Conversion3",
        "DisplayIngredients": "ReagentConverterT5",
        "CraftAll": true,
        "IsRefining": true,
        "CraftingFee": 100,
        "UseCraftingTax": 0,
        "Tradeskill": "Weaving",
        "RecipeLevel": 0,
        "StationType1": "weaving2",
        "OutputQty": 15,
        "ItemID": "SolventT5",
        "SkipGrantItems": false,
        "BaseTier": 0,
        "Ingredient1": "ReagentConverterT5",
        "Type1": "Item",
        "Ingredient2": "SolventReagentsT5",
        "Type2": "Category_Only",
        "Qty1": 1,
        "Qty2": 20,
        "Qty3": 0,
        "Qty4": 0,
        "Qty5": 0,
        "CooldownSeconds": 0,
        "CooldownQuantity": 0,
        "BonusItemChance": -0.3,
        "BonusItemChanceIncrease": "0,0,0,0,0",
        "BonusItemChanceDecrease": "0,0,0,0,0"
      },
      {
        "RecipeID": "Loom_TanninT5",
        "CraftingCategory": "MaterialConversion",
        "CraftingGroup": "Conversion3",
        "DisplayIngredients": "ReagentConverterT5",
        "CraftAll": true,
        "IsRefining": true,
        "CraftingFee": 100,
        "UseCraftingTax": 0,
        "Tradeskill": "Weaving",
        "RecipeLevel": 0,
        "StationType1": "weaving2",
        "OutputQty": 15,
        "ItemID": "TanninT5",
        "SkipGrantItems": false,
        "BaseTier": 0,
        "Ingredient1": "ReagentConverterT5",
        "Type1": "Item",
        "Ingredient2": "TanninReagentsT5",
        "Type2": "Category_Only",
        "Qty1": 1,
        "Qty2": 20,
        "Qty3": 0,
        "Qty4": 0,
        "Qty5": 0,
        "CooldownSeconds": 0,
        "CooldownQuantity": 0,
        "BonusItemChance": -0.3,
        "BonusItemChanceIncrease": "0,0,0,0,0",
        "BonusItemChanceDecrease": "0,0,0,0,0"
      },
      {
        "RecipeID": "Tannery_SandpaperT5",
        "CraftingCategory": "MaterialConversion",
        "CraftingGroup": "Conversion3",
        "DisplayIngredients": "ReagentConverterT5",
        "CraftAll": true,
        "IsRefining": true,
        "CraftingFee": 100,
        "UseCraftingTax": 0,
        "Tradeskill": "Leatherworking",
        "RecipeLevel": 0,
        "StationType1": "tanning2",
        "OutputQty": 15,
        "ItemID": "SandpaperT5",
        "SkipGrantItems": false,
        "BaseTier": 0,
        "Ingredient1": "ReagentConverterT5",
        "Type1": "Item",
        "Ingredient2": "SandpaperReagentsT5",
        "Type2": "Category_Only",
        "Qty1": 1,
        "Qty2": 20,
        "Qty3": 0,
        "Qty4": 0,
        "Qty5": 0,
        "CooldownSeconds": 0,
        "CooldownQuantity": 0,
        "BonusItemChance": -0.3,
        "BonusItemChanceIncrease": "0,0,0,0,0",
        "BonusItemChanceDecrease": "0,0,0,0,0"
      },
      {
        "RecipeID": "Tannery_FluxT5",
        "CraftingCategory": "MaterialConversion",
        "CraftingGroup": "Conversion3",
        "DisplayIngredients": "ReagentConverterT5",
        "CraftAll": true,
        "IsRefining": true,
        "CraftingFee": 100,
        "UseCraftingTax": 0,
        "Tradeskill": "Leatherworking",
        "RecipeLevel": 0,
        "StationType1": "tanning2",
        "OutputQty": 15,
        "ItemID": "FluxT5",
        "SkipGrantItems": false,
        "BaseTier": 0,
        "Ingredient1": "ReagentConverterT5",
        "Type1": "Item",
        "Ingredient2": "FluxReagentsT5",
        "Type2": "Category_Only",
        "Qty1": 1,
        "Qty2": 20,
        "Qty3": 0,
        "Qty4": 0,
        "Qty5": 0,
        "CooldownSeconds": 0,
        "CooldownQuantity": 0,
        "BonusItemChance": -0.3,
        "BonusItemChanceIncrease": "0,0,0,0,0",
        "BonusItemChanceDecrease": "0,0,0,0,0"
      },
      {
        "RecipeID": "Tannery_ClothWeaveT5",
        "CraftingCategory": "MaterialConversion",
        "CraftingGroup": "Conversion3",
        "DisplayIngredients": "ReagentConverterT5",
        "CraftAll": true,
        "IsRefining": true,
        "CraftingFee": 100,
        "UseCraftingTax": 0,
        "Tradeskill": "Leatherworking",
        "RecipeLevel": 0,
        "StationType1": "tanning2",
        "OutputQty": 15,
        "ItemID": "ClothWeaveT5",
        "SkipGrantItems": false,
        "BaseTier": 0,
        "Ingredient1": "ReagentConverterT5",
        "Type1": "Item",
        "Ingredient2": "ClothWeaveReagentsT5",
        "Type2": "Category_Only",
        "Qty1": 1,
        "Qty2": 20,
        "Qty3": 0,
        "Qty4": 0,
        "Qty5": 0,
        "CooldownSeconds": 0,
        "CooldownQuantity": 0,
        "BonusItemChance": -0.3,
        "BonusItemChanceIncrease": "0,0,0,0,0",
        "BonusItemChanceDecrease": "0,0,0,0,0"
      },
      {
        "RecipeID": "Tannery_SolventT5",
        "CraftingCategory": "MaterialConversion",
        "CraftingGroup": "Conversion3",
        "DisplayIngredients": "ReagentConverterT5",
        "CraftAll": true,
        "IsRefining": true,
        "CraftingFee": 100,
        "UseCraftingTax": 0,
        "Tradeskill": "Leatherworking",
        "RecipeLevel": 0,
        "StationType1": "tanning2",
        "OutputQty": 15,
        "ItemID": "SolventT5",
        "SkipGrantItems": false,
        "BaseTier": 0,
        "Ingredient1": "ReagentConverterT5",
        "Type1": "Item",
        "Ingredient2": "SolventReagentsT5",
        "Type2": "Category_Only",
        "Qty1": 1,
        "Qty2": 20,
        "Qty3": 0,
        "Qty4": 0,
        "Qty5": 0,
        "CooldownSeconds": 0,
        "CooldownQuantity": 0,
        "BonusItemChance": -0.3,
        "BonusItemChanceIncrease": "0,0,0,0,0",
        "BonusItemChanceDecrease": "0,0,0,0,0"
      },
      {
        "RecipeID": "Tannery_TanninT5",
        "CraftingCategory": "MaterialConversion",
        "CraftingGroup": "Conversion3",
        "DisplayIngredients": "ReagentConverterT5",
        "CraftAll": true,
        "IsRefining": true,
        "CraftingFee": 100,
        "UseCraftingTax": 0,
        "Tradeskill": "Leatherworking",
        "RecipeLevel": 0,
        "StationType1": "tanning2",
        "OutputQty": 15,
        "ItemID": "TanninT5",
        "SkipGrantItems": false,
        "BaseTier": 0,
        "Ingredient1": "ReagentConverterT5",
        "Type1": "Item",
        "Ingredient2": "TanninReagentsT5",
        "Type2": "Category_Only",
        "Qty1": 1,
        "Qty2": 20,
        "Qty3": 0,
        "Qty4": 0,
        "Qty5": 0,
        "CooldownSeconds": 0,
        "CooldownQuantity": 0,
        "BonusItemChance": -0.3,
        "BonusItemChanceIncrease": "0,0,0,0,0",
        "BonusItemChanceDecrease": "0,0,0,0,0"
      },
      {
        "RecipeID": "Woodworker_SandpaperT5",
        "CraftingCategory": "MaterialConversion",
        "CraftingGroup": "Conversion3",
        "DisplayIngredients": "ReagentConverterT5",
        "CraftAll": true,
        "IsRefining": true,
        "CraftingFee": 100,
        "UseCraftingTax": 0,
        "Tradeskill": "Woodworking",
        "RecipeLevel": 0,
        "StationType1": "carpentry2",
        "OutputQty": 15,
        "ItemID": "SandpaperT5",
        "SkipGrantItems": false,
        "BaseTier": 0,
        "Ingredient1": "ReagentConverterT5",
        "Type1": "Item",
        "Ingredient2": "SandpaperReagentsT5",
        "Type2": "Category_Only",
        "Qty1": 1,
        "Qty2": 20,
        "Qty3": 0,
        "Qty4": 0,
        "Qty5": 0,
        "CooldownSeconds": 0,
        "CooldownQuantity": 0,
        "BonusItemChance": -0.3,
        "BonusItemChanceIncrease": "0,0,0,0,0",
        "BonusItemChanceDecrease": "0,0,0,0,0"
      },
      {
        "RecipeID": "Woodworker_FluxT5",
        "CraftingCategory": "MaterialConversion",
        "CraftingGroup": "Conversion3",
        "DisplayIngredients": "ReagentConverterT5",
        "CraftAll": true,
        "IsRefining": true,
        "CraftingFee": 100,
        "UseCraftingTax": 0,
        "Tradeskill": "Woodworking",
        "RecipeLevel": 0,
        "StationType1": "carpentry2",
        "OutputQty": 15,
        "ItemID": "FluxT5",
        "SkipGrantItems": false,
        "BaseTier": 0,
        "Ingredient1": "ReagentConverterT5",
        "Type1": "Item",
        "Ingredient2": "FluxReagentsT5",
        "Type2": "Category_Only",
        "Qty1": 1,
        "Qty2": 20,
        "Qty3": 0,
        "Qty4": 0,
        "Qty5": 0,
        "CooldownSeconds": 0,
        "CooldownQuantity": 0,
        "BonusItemChance": -0.3,
        "BonusItemChanceIncrease": "0,0,0,0,0",
        "BonusItemChanceDecrease": "0,0,0,0,0"
      },
      {
        "RecipeID": "Woodworker_ClothWeaveT5",
        "CraftingCategory": "MaterialConversion",
        "CraftingGroup": "Conversion3",
        "DisplayIngredients": "ReagentConverterT5",
        "CraftAll": true,
        "IsRefining": true,
        "CraftingFee": 100,
        "UseCraftingTax": 0,
        "Tradeskill": "Woodworking",
        "RecipeLevel": 0,
        "StationType1": "carpentry2",
        "OutputQty": 15,
        "ItemID": "ClothWeaveT5",
        "SkipGrantItems": false,
        "BaseTier": 0,
        "Ingredient1": "ReagentConverterT5",
        "Type1": "Item",
        "Ingredient2": "ClothWeaveReagentsT5",
        "Type2": "Category_Only",
        "Qty1": 1,
        "Qty2": 20,
        "Qty3": 0,
        "Qty4": 0,
        "Qty5": 0,
        "CooldownSeconds": 0,
        "CooldownQuantity": 0,
        "BonusItemChance": -0.3,
        "BonusItemChanceIncrease": "0,0,0,0,0",
        "BonusItemChanceDecrease": "0,0,0,0,0"
      },
      {
        "RecipeID": "Woodworker_SolventT5",
        "CraftingCategory": "MaterialConversion",
        "CraftingGroup": "Conversion3",
        "DisplayIngredients": "ReagentConverterT5",
        "CraftAll": true,
        "IsRefining": true,
        "CraftingFee": 100,
        "UseCraftingTax": 0,
        "Tradeskill": "Woodworking",
        "RecipeLevel": 0,
        "StationType1": "carpentry2",
        "OutputQty": 15,
        "ItemID": "SolventT5",
        "SkipGrantItems": false,
        "BaseTier": 0,
        "Ingredient1": "ReagentConverterT5",
        "Type1": "Item",
        "Ingredient2": "SolventReagentsT5",
        "Type2": "Category_Only",
        "Qty1": 1,
        "Qty2": 20,
        "Qty3": 0,
        "Qty4": 0,
        "Qty5": 0,
        "CooldownSeconds": 0,
        "CooldownQuantity": 0,
        "BonusItemChance": -0.3,
        "BonusItemChanceIncrease": "0,0,0,0,0",
        "BonusItemChanceDecrease": "0,0,0,0,0"
      },
      {
        "RecipeID": "Woodworker_TanninT5",
        "CraftingCategory": "MaterialConversion",
        "CraftingGroup": "Conversion3",
        "DisplayIngredients": "ReagentConverterT5",
        "CraftAll": true,
        "IsRefining": true,
        "CraftingFee": 100,
        "UseCraftingTax": 0,
        "Tradeskill": "Woodworking",
        "RecipeLevel": 0,
        "StationType1": "carpentry2",
        "OutputQty": 15,
        "ItemID": "TanninT5",
        "SkipGrantItems": false,
        "BaseTier": 0,
        "Ingredient1": "ReagentConverterT5",
        "Type1": "Item",
        "Ingredient2": "TanninReagentsT5",
        "Type2": "Category_Only",
        "Qty1": 1,
        "Qty2": 20,
        "Qty3": 0,
        "Qty4": 0,
        "Qty5": 0,
        "CooldownSeconds": 0,
        "CooldownQuantity": 0,
        "BonusItemChance": -0.3,
        "BonusItemChanceIncrease": "0,0,0,0,0",
        "BonusItemChanceDecrease": "0,0,0,0,0"
      },
      {
        "RecipeID": "CharcoalT1",
        "CraftingCategory": "RefinedResources",
        "CraftingGroup": "Charcoal",
        "CraftAll": true,
        "IsRefining": true,
        "CraftingFee": 1,
        "UseCraftingTax": 0,
        "Tradeskill": "Smelting",
        "RecipeLevel": 0,
        "StationType1": "smelting2",
        "OutputQty": 1,
        "ItemID": "CharcoalT1",
        "SkipGrantItems": false,
        "BaseTier": 1,
        "Ingredient1": "Wood",
        "Type1": "Category_Only",
        "Qty1": 2,
        "CooldownSeconds": 0,
        "CooldownQuantity": 0,
        "BonusItemChance": 0,
        "BonusItemChanceIncrease": "0.5,1,1.5,2,3",
        "BonusItemChanceDecrease": "0,0,0,0,0"
      },
      {
        "RecipeID": "CharcoalT1_WoodenCoin",
        "CraftingCategory": "RefinedResources",
        "CraftingGroup": "Charcoal",
        "CraftAll": true,
        "IsRefining": true,
        "CraftingFee": 1,
        "UseCraftingTax": 0,
        "Tradeskill": "Smelting",
        "RecipeLevel": 75,
        "StationType1": "smelting2",
        "OutputQty": 10,
        "ItemID": "CharcoalT1",
        "SkipGrantItems": false,
        "BaseTier": 1,
        "Ingredient1": "WoodenCoin",
        "Type1": "Item",
        "Qty1": 1,
        "CooldownSeconds": 0,
        "CooldownQuantity": 0,
        "BonusItemChance": 0,
        "BonusItemChanceIncrease": "0.5,1,1.5,2,3",
        "BonusItemChanceDecrease": "0,0,0,0,0"
      },
      {
        "RecipeID": "House_HousingItem_Lighting_CandleHolder_A",
        "CraftingCategory": "Furniture",
        "CraftingGroup": "Decorations",
        "CraftAll": true,
        "IsRefining": true,
        "CraftingFee": 300,
        "UseCraftingTax": 1,
        "Tradeskill": "Furnishing",
        "RecipeLevel": 152,
        "StationType1": "engineering2",
        "OutputQty": 1,
        "ItemID": "House_HousingItem_Lighting_CandleHolder_A",
        "SkipGrantItems": false,
        "Ingredient1": "IngotT5",
        "Type1": "Item",
        "Ingredient2": "BeeswaxT1",
        "Type2": "Item",
        "Ingredient3": "AlchemyFireT1",
        "Type3": "Item",
        "Qty1": 15,
        "Qty2": 5,
        "Qty3": 1,
        "BonusItemChance": 0
      }
    ] satisfies Partial<CraftingRecipeTestData>[],
    [DATASHEETS.CraftingCategoryData.CraftingCategories.uri]: [
      {
        "CategoryID": "Solvent",
        "ImagePath": "lyshineui/images/icons/items/drawing/solvent.webp",
        "DisplayText": "@Solvent_GroupName"
      },
      {
        "CategoryID": "RefiningReagentsT5",
        "DisplayText": "@RefiningReagentsT5_GroupName"
      },
      {
        "CategoryID": "FluxReagentsT5",
        "ImagePath": "lyshineui/images/icons/items/drawing/refiningreagents.webp",
        "DisplayText": "@RefiningReagentsT5_GroupName"
      },
      {
        "CategoryID": "SolventReagentsT5",
        "ImagePath": "lyshineui/images/icons/items/drawing/refiningreagents.webp",
        "DisplayText": "@RefiningReagentsT5_GroupName"
      },
      {
        "CategoryID": "TanninReagentsT5",
        "ImagePath": "lyshineui/images/icons/items/drawing/refiningreagents.webp",
        "DisplayText": "@RefiningReagentsT5_GroupName"
      },
      {
        "CategoryID": "ClothWeaveReagentsT5",
        "DisplayText": "@RefiningReagentsT5_GroupName"
      },
      {
        "CategoryID": "SandpaperReagentsT5",
        "ImagePath": "lyshineui/images/icons/items/drawing/refiningreagents.webp",
        "DisplayText": "@RefiningReagentsT5_GroupName"
      },
      {
        "CategoryID": "Wood",
        "ImagePath": "lyshineui/images/icons/items/drawing/wood.webp",
        "DisplayText": "@Wood_CategoryName"
      },
      {
        "CategoryID": "Utilities",
        "ImagePath": "lyshineui/images/icons/crafting/icon_crafting_category_utilities.webp",
        "DisplayText": "@CategoryData_Utilities"
      }
    ] satisfies Partial<CraftingCategoryTestData>[]
  };

  private readonly _getDataSheet = <T>([key, value]: [string, DataSheetUri<T>]): Observable<Record<string, T[]>> => {
    return this.#async.invoke(key, of({ [key]: this.data[value.uri] as T[] }));
  }

  getTranslations(locale: string): Observable<Localization> {
    return this.#async.invoke(locale, of(locale === 'en-us' ? translationsEn : {}));
  }

  getDataSheets<T>(set: Record<string, DataSheetUri<T>>): Observable<Record<string, T[]>> {
    return from(Object.entries(set)).pipe(mergeMap(this._getDataSheet), reduce(mergeData, {}));
  }

  defer(mode: boolean): void {
    return this.#async.defer(mode);
  }

  complete(...ids: string[]): void {
    return this.#async.complete(...ids);
  }

  completeAll(): void {
    return this.#async.completeAll();
  }
}
