# The deployment workflow that is triggered on pushed and PR integration
name: Deployment

on:
  release:
    types: [ published ]

permissions:
  pages: write
  id-token: write

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/build.yml
    with:
      package-name: arthisan
      upload-artifacts: true

  cd:
    name: CD
    uses: ./.github/workflows/deploy.yml
    needs: ci

